// Code generated by hertz generator.

package auth

import (
	"context"

	auth "github.com/PiaoAdmin/pmall/app/api/biz/model/api/auth"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/auth"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// Register .
// @Summary      用户注册
// @Description  Create a new user account with username, password, email etc.
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Param        req  body      auth.RegisterReq  true  "Register Request"
// @Success      200  {object}  response.Response{data=auth.RegisterResp}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewRegisterService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// Login .
// @Summary      用户登录
// @Description  Login with username and password to get JWT token
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Param        req  body      auth.LoginReq  true  "Login Request"
// @Success      200  {object}  response.Response{data=auth.LoginResp}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewLoginService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// Logout .
// @Summary      用户登出
// @Description  Logout current user (Clear cookie if enabled)
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Param        Authorization header string true "Bearer {token}"
// @Success      200  {object}  response.Response
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	_, err = service.NewLogoutService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, nil)
}

// GetUserInfo .
// @Summary      获取用户信息
// @Description  Get current logged-in user's profile
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Security     ApiKeyAuth
// @Param        Authorization header string true "Bearer {token}"
// @Success      200  {object}  response.Response{data=auth.GetUserInfoResp}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /auth/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.GetUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewGetUserInfoService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// UpdateUser .
// @Summary      更新用户信息
// @Description  Update user profile (email, phone, etc.)
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Security     ApiKeyAuth
// @Param        Authorization header string true "Bearer {token}"
// @Param        req  body      auth.UpdateUserReq  true  "Update Request"
// @Success      200  {object}  response.Response{data=auth.Empty}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /auth/update [POST]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.UpdateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewUpdateUserService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// UpdatePassword .
// @Summary      修改密码
// @Description  Update account password
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Security     ApiKeyAuth
// @Param        Authorization header string true "Bearer {token}"
// @Param        req  body      auth.UpdatePasswordReq  true  "Update Password Request"
// @Success      200  {object}  response.Response{data=auth.Empty}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /auth/password [POST]
func UpdatePassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.UpdatePasswordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewUpdatePasswordService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// RefreshToken .
// @Summary      刷新 Token
// @Description  Refresh expired token to get a new one
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Param        Authorization header string true "Bearer {token}"
// @Success      200  {object}  response.Response{data=auth.RefreshResp}
// @Failure      401  {object}  response.Response{data=string}  "Unauthorized"
// @Router       /refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewRefreshTokenService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
