// Code generated by Kitex v0.15.4. DO NOT EDIT.

package payment

import (
	"context"

	"github.com/cloudwego/prutal"
)

type PayRequest struct {
	OrderId    string `protobuf:"bytes,1,opt,name=order_id" json:"order_id,omitempty"`
	UserId     uint64 `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	Amount     string `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
	CreditCard string `protobuf:"bytes,4,opt,name=credit_card" json:"credit_card,omitempty"`
}

func (x *PayRequest) Reset() { *x = PayRequest{} }

func (x *PayRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PayRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PayRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PayRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PayRequest) GetCreditCard() string {
	if x != nil {
		return x.CreditCard
	}
	return ""
}

type PayResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	TradeNo string `protobuf:"bytes,2,opt,name=trade_no" json:"trade_no,omitempty"`
}

func (x *PayResponse) Reset() { *x = PayResponse{} }

func (x *PayResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PayResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayResponse) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type PaymentService interface {
	Pay(ctx context.Context, req *PayRequest) (res *PayResponse, err error)
}
