// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: cart_api.proto

package cart

import (
	_ "github.com/PiaoAdmin/pmall/app/api/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 购物车项模型
type CartItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId       uint64 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" form:"sku_id" json:"sku_id,omitempty" query:"sku_id"`
	Quantity    int32  `protobuf:"varint,2,opt,name=quantity,proto3" form:"quantity" json:"quantity,omitempty" query:"quantity"`
	SkuName     string `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" form:"sku_name" json:"sku_name,omitempty" query:"sku_name"`
	SkuImage    string `protobuf:"bytes,4,opt,name=sku_image,json=skuImage,proto3" form:"sku_image" json:"sku_image,omitempty" query:"sku_image"`
	Price       string `protobuf:"bytes,5,opt,name=price,proto3" form:"price" json:"price,omitempty" query:"price"`
	MarketPrice string `protobuf:"bytes,6,opt,name=market_price,json=marketPrice,proto3" form:"market_price" json:"market_price,omitempty" query:"market_price"`
	Stock       int32  `protobuf:"varint,7,opt,name=stock,proto3" form:"stock" json:"stock,omitempty" query:"stock"`
	SpuId       uint64 `protobuf:"varint,8,opt,name=spu_id,json=spuId,proto3" form:"spu_id" json:"spu_id,omitempty" query:"spu_id"`
	SpuName     string `protobuf:"bytes,9,opt,name=spu_name,json=spuName,proto3" form:"spu_name" json:"spu_name,omitempty" query:"spu_name"`
	SkuSpecData string `protobuf:"bytes,10,opt,name=sku_spec_data,json=skuSpecData,proto3" form:"sku_spec_data" json:"sku_spec_data,omitempty" query:"sku_spec_data"`
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CartItem) GetSkuImage() string {
	if x != nil {
		return x.SkuImage
	}
	return ""
}

func (x *CartItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CartItem) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *CartItem) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CartItem) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CartItem) GetSpuName() string {
	if x != nil {
		return x.SpuName
	}
	return ""
}

func (x *CartItem) GetSkuSpecData() string {
	if x != nil {
		return x.SkuSpecData
	}
	return ""
}

// 添加到购物车
type AddToCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId    uint64 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" form:"sku_id" json:"sku_id,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" form:"quantity" json:"quantity,omitempty"`
}

func (x *AddToCartReq) Reset() {
	*x = AddToCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartReq) ProtoMessage() {}

func (x *AddToCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartReq.ProtoReflect.Descriptor instead.
func (*AddToCartReq) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{1}
}

func (x *AddToCartReq) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AddToCartReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddToCartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartItem *CartItem `protobuf:"bytes,1,opt,name=cart_item,json=cartItem,proto3" form:"cart_item" json:"cart_item,omitempty" query:"cart_item"`
}

func (x *AddToCartResp) Reset() {
	*x = AddToCartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartResp) ProtoMessage() {}

func (x *AddToCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartResp.ProtoReflect.Descriptor instead.
func (*AddToCartResp) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{2}
}

func (x *AddToCartResp) GetCartItem() *CartItem {
	if x != nil {
		return x.CartItem
	}
	return nil
}

// 从购物车移除
type RemoveFromCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuIds []uint64 `protobuf:"varint,1,rep,packed,name=sku_ids,json=skuIds,proto3" form:"sku_ids" json:"sku_ids,omitempty"`
}

func (x *RemoveFromCartReq) Reset() {
	*x = RemoveFromCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartReq) ProtoMessage() {}

func (x *RemoveFromCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartReq.ProtoReflect.Descriptor instead.
func (*RemoveFromCartReq) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFromCartReq) GetSkuIds() []uint64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type RemoveFromCartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" form:"success" json:"success,omitempty" query:"success"`
}

func (x *RemoveFromCartResp) Reset() {
	*x = RemoveFromCartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartResp) ProtoMessage() {}

func (x *RemoveFromCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartResp.ProtoReflect.Descriptor instead.
func (*RemoveFromCartResp) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFromCartResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取购物车详情
type GetCartDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCartDetailsReq) Reset() {
	*x = GetCartDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCartDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartDetailsReq) ProtoMessage() {}

func (x *GetCartDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartDetailsReq.ProtoReflect.Descriptor instead.
func (*GetCartDetailsReq) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{5}
}

type GetCartDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items         []*CartItem `protobuf:"bytes,1,rep,name=items,proto3" form:"items" json:"items,omitempty" query:"items"`
	TotalQuantity int32       `protobuf:"varint,2,opt,name=total_quantity,json=totalQuantity,proto3" form:"total_quantity" json:"total_quantity,omitempty" query:"total_quantity"`
	TotalAmount   string      `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" form:"total_amount" json:"total_amount,omitempty" query:"total_amount"`
}

func (x *GetCartDetailsResp) Reset() {
	*x = GetCartDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCartDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartDetailsResp) ProtoMessage() {}

func (x *GetCartDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartDetailsResp.ProtoReflect.Descriptor instead.
func (*GetCartDetailsResp) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetCartDetailsResp) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCartDetailsResp) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *GetCartDetailsResp) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

// 清空购物车
type ClearCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearCartReq) Reset() {
	*x = ClearCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartReq) ProtoMessage() {}

func (x *ClearCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartReq.ProtoReflect.Descriptor instead.
func (*ClearCartReq) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{7}
}

type ClearCartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" form:"success" json:"success,omitempty" query:"success"`
}

func (x *ClearCartResp) Reset() {
	*x = ClearCartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cart_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResp) ProtoMessage() {}

func (x *ClearCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResp.ProtoReflect.Descriptor instead.
func (*ClearCartResp) Descriptor() ([]byte, []int) {
	return file_cart_api_proto_rawDescGZIP(), []int{8}
}

func (x *ClearCartResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_cart_api_proto protoreflect.FileDescriptor

var file_cart_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x1a, 0x09,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x02, 0x0a, 0x08, 0x43, 0x61,
	0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x75, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x75, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6b, 0x75, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6b, 0x75, 0x53, 0x70,
	0x65, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x0a, 0xca, 0xbb, 0x18, 0x06, 0x73, 0x6b, 0x75, 0x5f,
	0x69, 0x64, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0c, 0xca, 0xbb, 0x18,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x44, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x08, 0x63, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x39, 0x0a, 0x11, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x24,
	0x0a, 0x07, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x42,
	0x0b, 0xca, 0xbb, 0x18, 0x07, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x73, 0x52, 0x06, 0x73, 0x6b,
	0x75, 0x49, 0x64, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43,
	0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x22, 0x29, 0x0a, 0x0d, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x32, 0x80, 0x03, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74,
	0x12, 0x1a, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e,
	0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54,
	0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0d, 0xd2, 0xc1, 0x18, 0x09, 0x2f,
	0x63, 0x61, 0x72, 0x74, 0x2f, 0x61, 0x64, 0x64, 0x12, 0x65, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x10, 0xd2,
	0xc1, 0x18, 0x0c, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12,
	0x5e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x1f, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x20, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x09, 0xca, 0xc1, 0x18, 0x05, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x12,
	0x55, 0x0a, 0x09, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0f, 0xd2, 0xc1, 0x18, 0x0b, 0x2f, 0x63, 0x61, 0x72, 0x74,
	0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x69, 0x61, 0x6f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x70,
	0x6d, 0x61, 0x6c, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cart_api_proto_rawDescOnce sync.Once
	file_cart_api_proto_rawDescData = file_cart_api_proto_rawDesc
)

func file_cart_api_proto_rawDescGZIP() []byte {
	file_cart_api_proto_rawDescOnce.Do(func() {
		file_cart_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_cart_api_proto_rawDescData)
	})
	return file_cart_api_proto_rawDescData
}

var file_cart_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cart_api_proto_goTypes = []interface{}{
	(*CartItem)(nil),           // 0: gateway.cart.CartItem
	(*AddToCartReq)(nil),       // 1: gateway.cart.AddToCartReq
	(*AddToCartResp)(nil),      // 2: gateway.cart.AddToCartResp
	(*RemoveFromCartReq)(nil),  // 3: gateway.cart.RemoveFromCartReq
	(*RemoveFromCartResp)(nil), // 4: gateway.cart.RemoveFromCartResp
	(*GetCartDetailsReq)(nil),  // 5: gateway.cart.GetCartDetailsReq
	(*GetCartDetailsResp)(nil), // 6: gateway.cart.GetCartDetailsResp
	(*ClearCartReq)(nil),       // 7: gateway.cart.ClearCartReq
	(*ClearCartResp)(nil),      // 8: gateway.cart.ClearCartResp
}
var file_cart_api_proto_depIdxs = []int32{
	0, // 0: gateway.cart.AddToCartResp.cart_item:type_name -> gateway.cart.CartItem
	0, // 1: gateway.cart.GetCartDetailsResp.items:type_name -> gateway.cart.CartItem
	1, // 2: gateway.cart.CartService.AddToCart:input_type -> gateway.cart.AddToCartReq
	3, // 3: gateway.cart.CartService.RemoveFromCart:input_type -> gateway.cart.RemoveFromCartReq
	5, // 4: gateway.cart.CartService.GetCartDetails:input_type -> gateway.cart.GetCartDetailsReq
	7, // 5: gateway.cart.CartService.ClearCart:input_type -> gateway.cart.ClearCartReq
	2, // 6: gateway.cart.CartService.AddToCart:output_type -> gateway.cart.AddToCartResp
	4, // 7: gateway.cart.CartService.RemoveFromCart:output_type -> gateway.cart.RemoveFromCartResp
	6, // 8: gateway.cart.CartService.GetCartDetails:output_type -> gateway.cart.GetCartDetailsResp
	8, // 9: gateway.cart.CartService.ClearCart:output_type -> gateway.cart.ClearCartResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cart_api_proto_init() }
func file_cart_api_proto_init() {
	if File_cart_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cart_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromCartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCartDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCartDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cart_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearCartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cart_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_api_proto_goTypes,
		DependencyIndexes: file_cart_api_proto_depIdxs,
		MessageInfos:      file_cart_api_proto_msgTypes,
	}.Build()
	File_cart_api_proto = out.File
	file_cart_api_proto_rawDesc = nil
	file_cart_api_proto_goTypes = nil
	file_cart_api_proto_depIdxs = nil
}
