// Code generated by hertz generator.

package main

import (
	"io"
	"os"

	"github.com/PiaoAdmin/pmall/app/api/biz/dal"
	"github.com/PiaoAdmin/pmall/app/api/conf"
	_ "github.com/PiaoAdmin/pmall/app/api/docs"
	mwError "github.com/PiaoAdmin/pmall/app/api/md/error"
	"github.com/PiaoAdmin/pmall/app/api/md/jwt"
	"github.com/PiaoAdmin/pmall/app/api/rpc"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/adaptor"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title           P-Mall API
// @version         1.0
// @description     This is a p-mall server.
// @host            localhost:8888
// @BasePath        /
func main() {
	dal.Init()
	rpc.Init()
	jwt.Init()
	address := conf.GetConf().Hertz.Address
	f, err := os.OpenFile("./output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	fileWriter := io.MultiWriter(f, os.Stdout)
	hlog.SetOutput(fileWriter)
	h := server.New(server.WithHostPorts(address))
	h.Use(mwError.GlobalErrorHandler())

	// Swagger API docs route
	h.GET("/swagger/*any", adaptor.HertzHandler(
		httpSwagger.WrapHandler,
	))

	register(h)
	h.Spin()
}
