// Code generated by Kitex v0.9.1. DO NOT EDIT.

package orderservice

import (
<<<<<<< HEAD
	// order "douyin-gomall/gomall/rpc_gen/kitex_gen/order"
=======
>>>>>>> b6e73c27fce12b01552c5334097a847176b8f26a
	order "github.com/PiaoAdmin/gomall/rpc_gen/kitex_gen/order"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler order.OrderService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
