// Code generated by Kitex v0.9.1. DO NOT EDIT.
package orderservice

import (
<<<<<<< HEAD
	// order "douyin-gomall/gomall/rpc_gen/kitex_gen/order"
=======
>>>>>>> b6e73c27fce12b01552c5334097a847176b8f26a
	order "github.com/PiaoAdmin/gomall/rpc_gen/kitex_gen/order"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler order.OrderService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler order.OrderService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
