// Code generated by Kitex v0.15.4. DO NOT EDIT.

package productservice

import (
	"context"
	product "github.com/PiaoAdmin/pmall/rpc_gen/product"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateProduct(ctx context.Context, Req *product.CreateProductRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error)
	UpdateProduct(ctx context.Context, Req *product.UpdateProductRequest, callOptions ...callopt.Option) (r *product.UpdateProductResponse, err error)
	UpdateProductStatus(ctx context.Context, Req *product.UpdateProductStatusRequest, callOptions ...callopt.Option) (r *product.UpdateProductStatusResponse, err error)
	GetProductDetail(ctx context.Context, Req *product.GetProductDetailRequest, callOptions ...callopt.Option) (r *product.GetProductDetailResponse, err error)
	ListProducts(ctx context.Context, Req *product.ListProductsRequest, callOptions ...callopt.Option) (r *product.ListProductsResponse, err error)
	GetProductsByIds(ctx context.Context, Req *product.GetProductsByIdsRequest, callOptions ...callopt.Option) (r *product.GetProductsByIdsResponse, err error)
	GetSkusByIds(ctx context.Context, Req *product.GetSkusByIdsRequest, callOptions ...callopt.Option) (r *product.GetSkusByIdsResponse, err error)
	BatchUpdateSku(ctx context.Context, Req *product.BatchUpdateSkuRequest, callOptions ...callopt.Option) (r *product.BatchUpdateSkuResponse, err error)
	DeductStock(ctx context.Context, Req *product.DeductStockRequest, callOptions ...callopt.Option) (r *product.DeductStockResponse, err error)
	ReleaseStock(ctx context.Context, Req *product.ReleaseStockRequest, callOptions ...callopt.Option) (r *product.ReleaseStockResponse, err error)
	ListCategories(ctx context.Context, Req *product.ListCategoriesRequest, callOptions ...callopt.Option) (r *product.ListCategoriesResponse, err error)
	ListBrands(ctx context.Context, Req *product.ListBrandsRequest, callOptions ...callopt.Option) (r *product.ListBrandsResponse, err error)
	SearchProducts(ctx context.Context, Req *product.SearchProductsRequest, callOptions ...callopt.Option) (r *product.SearchProductsResponse, err error)
	GetHotProducts(ctx context.Context, Req *product.GetHotProductsRequest, callOptions ...callopt.Option) (r *product.GetHotProductsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kProductServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProductServiceClient struct {
	*kClient
}

func (p *kProductServiceClient) CreateProduct(ctx context.Context, Req *product.CreateProductRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateProduct(ctx, Req)
}

func (p *kProductServiceClient) UpdateProduct(ctx context.Context, Req *product.UpdateProductRequest, callOptions ...callopt.Option) (r *product.UpdateProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProduct(ctx, Req)
}

func (p *kProductServiceClient) UpdateProductStatus(ctx context.Context, Req *product.UpdateProductStatusRequest, callOptions ...callopt.Option) (r *product.UpdateProductStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProductStatus(ctx, Req)
}

func (p *kProductServiceClient) GetProductDetail(ctx context.Context, Req *product.GetProductDetailRequest, callOptions ...callopt.Option) (r *product.GetProductDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProductDetail(ctx, Req)
}

func (p *kProductServiceClient) ListProducts(ctx context.Context, Req *product.ListProductsRequest, callOptions ...callopt.Option) (r *product.ListProductsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListProducts(ctx, Req)
}

func (p *kProductServiceClient) GetProductsByIds(ctx context.Context, Req *product.GetProductsByIdsRequest, callOptions ...callopt.Option) (r *product.GetProductsByIdsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProductsByIds(ctx, Req)
}

func (p *kProductServiceClient) GetSkusByIds(ctx context.Context, Req *product.GetSkusByIdsRequest, callOptions ...callopt.Option) (r *product.GetSkusByIdsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSkusByIds(ctx, Req)
}

func (p *kProductServiceClient) BatchUpdateSku(ctx context.Context, Req *product.BatchUpdateSkuRequest, callOptions ...callopt.Option) (r *product.BatchUpdateSkuResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchUpdateSku(ctx, Req)
}

func (p *kProductServiceClient) DeductStock(ctx context.Context, Req *product.DeductStockRequest, callOptions ...callopt.Option) (r *product.DeductStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeductStock(ctx, Req)
}

func (p *kProductServiceClient) ReleaseStock(ctx context.Context, Req *product.ReleaseStockRequest, callOptions ...callopt.Option) (r *product.ReleaseStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseStock(ctx, Req)
}

func (p *kProductServiceClient) ListCategories(ctx context.Context, Req *product.ListCategoriesRequest, callOptions ...callopt.Option) (r *product.ListCategoriesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCategories(ctx, Req)
}

func (p *kProductServiceClient) ListBrands(ctx context.Context, Req *product.ListBrandsRequest, callOptions ...callopt.Option) (r *product.ListBrandsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBrands(ctx, Req)
}

func (p *kProductServiceClient) SearchProducts(ctx context.Context, Req *product.SearchProductsRequest, callOptions ...callopt.Option) (r *product.SearchProductsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchProducts(ctx, Req)
}

func (p *kProductServiceClient) GetHotProducts(ctx context.Context, Req *product.GetHotProductsRequest, callOptions ...callopt.Option) (r *product.GetHotProductsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHotProducts(ctx, Req)
}
