// Code generated by Kitex v0.15.4. DO NOT EDIT.

package productservice

import (
	"context"
	"errors"
	product "github.com/PiaoAdmin/pmall/rpc_gen/product"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateProduct": kitex.NewMethodInfo(
		createProductHandler,
		newCreateProductArgs,
		newCreateProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateProduct": kitex.NewMethodInfo(
		updateProductHandler,
		newUpdateProductArgs,
		newUpdateProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateProductStatus": kitex.NewMethodInfo(
		updateProductStatusHandler,
		newUpdateProductStatusArgs,
		newUpdateProductStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetProductDetail": kitex.NewMethodInfo(
		getProductDetailHandler,
		newGetProductDetailArgs,
		newGetProductDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListProducts": kitex.NewMethodInfo(
		listProductsHandler,
		newListProductsArgs,
		newListProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetProductsByIds": kitex.NewMethodInfo(
		getProductsByIdsHandler,
		newGetProductsByIdsArgs,
		newGetProductsByIdsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetSkusByIds": kitex.NewMethodInfo(
		getSkusByIdsHandler,
		newGetSkusByIdsArgs,
		newGetSkusByIdsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchUpdateSku": kitex.NewMethodInfo(
		batchUpdateSkuHandler,
		newBatchUpdateSkuArgs,
		newBatchUpdateSkuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeductStock": kitex.NewMethodInfo(
		deductStockHandler,
		newDeductStockArgs,
		newDeductStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ReleaseStock": kitex.NewMethodInfo(
		releaseStockHandler,
		newReleaseStockArgs,
		newReleaseStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListCategories": kitex.NewMethodInfo(
		listCategoriesHandler,
		newListCategoriesArgs,
		newListCategoriesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListBrands": kitex.NewMethodInfo(
		listBrandsHandler,
		newListBrandsArgs,
		newListBrandsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchProducts": kitex.NewMethodInfo(
		searchProductsHandler,
		newSearchProductsArgs,
		newSearchProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetHotProducts": kitex.NewMethodInfo(
		getHotProductsHandler,
		newGetHotProductsArgs,
		newGetHotProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	productServiceServiceInfo                = NewServiceInfo()
	productServiceServiceInfoForClient       = NewServiceInfoForClient()
	productServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductService"
	handlerType := (*product.ProductService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "product",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func createProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.CreateProductRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).CreateProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateProductArgs:
		success, err := handler.(product.ProductService).CreateProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateProductArgs() interface{} {
	return &CreateProductArgs{}
}

func newCreateProductResult() interface{} {
	return &CreateProductResult{}
}

type CreateProductArgs struct {
	Req *product.CreateProductRequest
}

func (p *CreateProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateProductArgs) Unmarshal(in []byte) error {
	msg := new(product.CreateProductRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateProductArgs_Req_DEFAULT *product.CreateProductRequest

func (p *CreateProductArgs) GetReq() *product.CreateProductRequest {
	if !p.IsSetReq() {
		return CreateProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateProductResult struct {
	Success *product.CreateProductResponse
}

var CreateProductResult_Success_DEFAULT *product.CreateProductResponse

func (p *CreateProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateProductResult) Unmarshal(in []byte) error {
	msg := new(product.CreateProductResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateProductResult) GetSuccess() *product.CreateProductResponse {
	if !p.IsSetSuccess() {
		return CreateProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.CreateProductResponse)
}

func (p *CreateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateProductResult) GetResult() interface{} {
	return p.Success
}

func updateProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.UpdateProductRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).UpdateProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateProductArgs:
		success, err := handler.(product.ProductService).UpdateProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateProductArgs() interface{} {
	return &UpdateProductArgs{}
}

func newUpdateProductResult() interface{} {
	return &UpdateProductResult{}
}

type UpdateProductArgs struct {
	Req *product.UpdateProductRequest
}

func (p *UpdateProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateProductArgs) Unmarshal(in []byte) error {
	msg := new(product.UpdateProductRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateProductArgs_Req_DEFAULT *product.UpdateProductRequest

func (p *UpdateProductArgs) GetReq() *product.UpdateProductRequest {
	if !p.IsSetReq() {
		return UpdateProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateProductResult struct {
	Success *product.UpdateProductResponse
}

var UpdateProductResult_Success_DEFAULT *product.UpdateProductResponse

func (p *UpdateProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateProductResult) Unmarshal(in []byte) error {
	msg := new(product.UpdateProductResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateProductResult) GetSuccess() *product.UpdateProductResponse {
	if !p.IsSetSuccess() {
		return UpdateProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.UpdateProductResponse)
}

func (p *UpdateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateProductResult) GetResult() interface{} {
	return p.Success
}

func updateProductStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.UpdateProductStatusRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).UpdateProductStatus(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateProductStatusArgs:
		success, err := handler.(product.ProductService).UpdateProductStatus(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateProductStatusResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateProductStatusArgs() interface{} {
	return &UpdateProductStatusArgs{}
}

func newUpdateProductStatusResult() interface{} {
	return &UpdateProductStatusResult{}
}

type UpdateProductStatusArgs struct {
	Req *product.UpdateProductStatusRequest
}

func (p *UpdateProductStatusArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateProductStatusArgs) Unmarshal(in []byte) error {
	msg := new(product.UpdateProductStatusRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateProductStatusArgs_Req_DEFAULT *product.UpdateProductStatusRequest

func (p *UpdateProductStatusArgs) GetReq() *product.UpdateProductStatusRequest {
	if !p.IsSetReq() {
		return UpdateProductStatusArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateProductStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateProductStatusArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateProductStatusResult struct {
	Success *product.UpdateProductStatusResponse
}

var UpdateProductStatusResult_Success_DEFAULT *product.UpdateProductStatusResponse

func (p *UpdateProductStatusResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateProductStatusResult) Unmarshal(in []byte) error {
	msg := new(product.UpdateProductStatusResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateProductStatusResult) GetSuccess() *product.UpdateProductStatusResponse {
	if !p.IsSetSuccess() {
		return UpdateProductStatusResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateProductStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.UpdateProductStatusResponse)
}

func (p *UpdateProductStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateProductStatusResult) GetResult() interface{} {
	return p.Success
}

func getProductDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.GetProductDetailRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).GetProductDetail(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetProductDetailArgs:
		success, err := handler.(product.ProductService).GetProductDetail(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetProductDetailResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetProductDetailArgs() interface{} {
	return &GetProductDetailArgs{}
}

func newGetProductDetailResult() interface{} {
	return &GetProductDetailResult{}
}

type GetProductDetailArgs struct {
	Req *product.GetProductDetailRequest
}

func (p *GetProductDetailArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetProductDetailArgs) Unmarshal(in []byte) error {
	msg := new(product.GetProductDetailRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetProductDetailArgs_Req_DEFAULT *product.GetProductDetailRequest

func (p *GetProductDetailArgs) GetReq() *product.GetProductDetailRequest {
	if !p.IsSetReq() {
		return GetProductDetailArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetProductDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetProductDetailArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetProductDetailResult struct {
	Success *product.GetProductDetailResponse
}

var GetProductDetailResult_Success_DEFAULT *product.GetProductDetailResponse

func (p *GetProductDetailResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetProductDetailResult) Unmarshal(in []byte) error {
	msg := new(product.GetProductDetailResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetProductDetailResult) GetSuccess() *product.GetProductDetailResponse {
	if !p.IsSetSuccess() {
		return GetProductDetailResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetProductDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.GetProductDetailResponse)
}

func (p *GetProductDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetProductDetailResult) GetResult() interface{} {
	return p.Success
}

func listProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.ListProductsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).ListProducts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListProductsArgs:
		success, err := handler.(product.ProductService).ListProducts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListProductsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListProductsArgs() interface{} {
	return &ListProductsArgs{}
}

func newListProductsResult() interface{} {
	return &ListProductsResult{}
}

type ListProductsArgs struct {
	Req *product.ListProductsRequest
}

func (p *ListProductsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListProductsArgs) Unmarshal(in []byte) error {
	msg := new(product.ListProductsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListProductsArgs_Req_DEFAULT *product.ListProductsRequest

func (p *ListProductsArgs) GetReq() *product.ListProductsRequest {
	if !p.IsSetReq() {
		return ListProductsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListProductsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListProductsResult struct {
	Success *product.ListProductsResponse
}

var ListProductsResult_Success_DEFAULT *product.ListProductsResponse

func (p *ListProductsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListProductsResult) Unmarshal(in []byte) error {
	msg := new(product.ListProductsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListProductsResult) GetSuccess() *product.ListProductsResponse {
	if !p.IsSetSuccess() {
		return ListProductsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.ListProductsResponse)
}

func (p *ListProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListProductsResult) GetResult() interface{} {
	return p.Success
}

func getProductsByIdsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.GetProductsByIdsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).GetProductsByIds(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetProductsByIdsArgs:
		success, err := handler.(product.ProductService).GetProductsByIds(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetProductsByIdsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetProductsByIdsArgs() interface{} {
	return &GetProductsByIdsArgs{}
}

func newGetProductsByIdsResult() interface{} {
	return &GetProductsByIdsResult{}
}

type GetProductsByIdsArgs struct {
	Req *product.GetProductsByIdsRequest
}

func (p *GetProductsByIdsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetProductsByIdsArgs) Unmarshal(in []byte) error {
	msg := new(product.GetProductsByIdsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetProductsByIdsArgs_Req_DEFAULT *product.GetProductsByIdsRequest

func (p *GetProductsByIdsArgs) GetReq() *product.GetProductsByIdsRequest {
	if !p.IsSetReq() {
		return GetProductsByIdsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetProductsByIdsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetProductsByIdsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetProductsByIdsResult struct {
	Success *product.GetProductsByIdsResponse
}

var GetProductsByIdsResult_Success_DEFAULT *product.GetProductsByIdsResponse

func (p *GetProductsByIdsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetProductsByIdsResult) Unmarshal(in []byte) error {
	msg := new(product.GetProductsByIdsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetProductsByIdsResult) GetSuccess() *product.GetProductsByIdsResponse {
	if !p.IsSetSuccess() {
		return GetProductsByIdsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetProductsByIdsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.GetProductsByIdsResponse)
}

func (p *GetProductsByIdsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetProductsByIdsResult) GetResult() interface{} {
	return p.Success
}

func getSkusByIdsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.GetSkusByIdsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).GetSkusByIds(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSkusByIdsArgs:
		success, err := handler.(product.ProductService).GetSkusByIds(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSkusByIdsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSkusByIdsArgs() interface{} {
	return &GetSkusByIdsArgs{}
}

func newGetSkusByIdsResult() interface{} {
	return &GetSkusByIdsResult{}
}

type GetSkusByIdsArgs struct {
	Req *product.GetSkusByIdsRequest
}

func (p *GetSkusByIdsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSkusByIdsArgs) Unmarshal(in []byte) error {
	msg := new(product.GetSkusByIdsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSkusByIdsArgs_Req_DEFAULT *product.GetSkusByIdsRequest

func (p *GetSkusByIdsArgs) GetReq() *product.GetSkusByIdsRequest {
	if !p.IsSetReq() {
		return GetSkusByIdsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSkusByIdsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSkusByIdsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSkusByIdsResult struct {
	Success *product.GetSkusByIdsResponse
}

var GetSkusByIdsResult_Success_DEFAULT *product.GetSkusByIdsResponse

func (p *GetSkusByIdsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSkusByIdsResult) Unmarshal(in []byte) error {
	msg := new(product.GetSkusByIdsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSkusByIdsResult) GetSuccess() *product.GetSkusByIdsResponse {
	if !p.IsSetSuccess() {
		return GetSkusByIdsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSkusByIdsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.GetSkusByIdsResponse)
}

func (p *GetSkusByIdsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSkusByIdsResult) GetResult() interface{} {
	return p.Success
}

func batchUpdateSkuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.BatchUpdateSkuRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).BatchUpdateSku(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchUpdateSkuArgs:
		success, err := handler.(product.ProductService).BatchUpdateSku(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchUpdateSkuResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchUpdateSkuArgs() interface{} {
	return &BatchUpdateSkuArgs{}
}

func newBatchUpdateSkuResult() interface{} {
	return &BatchUpdateSkuResult{}
}

type BatchUpdateSkuArgs struct {
	Req *product.BatchUpdateSkuRequest
}

func (p *BatchUpdateSkuArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchUpdateSkuArgs) Unmarshal(in []byte) error {
	msg := new(product.BatchUpdateSkuRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchUpdateSkuArgs_Req_DEFAULT *product.BatchUpdateSkuRequest

func (p *BatchUpdateSkuArgs) GetReq() *product.BatchUpdateSkuRequest {
	if !p.IsSetReq() {
		return BatchUpdateSkuArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchUpdateSkuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchUpdateSkuArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchUpdateSkuResult struct {
	Success *product.BatchUpdateSkuResponse
}

var BatchUpdateSkuResult_Success_DEFAULT *product.BatchUpdateSkuResponse

func (p *BatchUpdateSkuResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchUpdateSkuResult) Unmarshal(in []byte) error {
	msg := new(product.BatchUpdateSkuResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchUpdateSkuResult) GetSuccess() *product.BatchUpdateSkuResponse {
	if !p.IsSetSuccess() {
		return BatchUpdateSkuResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchUpdateSkuResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.BatchUpdateSkuResponse)
}

func (p *BatchUpdateSkuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchUpdateSkuResult) GetResult() interface{} {
	return p.Success
}

func deductStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.DeductStockRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).DeductStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeductStockArgs:
		success, err := handler.(product.ProductService).DeductStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeductStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeductStockArgs() interface{} {
	return &DeductStockArgs{}
}

func newDeductStockResult() interface{} {
	return &DeductStockResult{}
}

type DeductStockArgs struct {
	Req *product.DeductStockRequest
}

func (p *DeductStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeductStockArgs) Unmarshal(in []byte) error {
	msg := new(product.DeductStockRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeductStockArgs_Req_DEFAULT *product.DeductStockRequest

func (p *DeductStockArgs) GetReq() *product.DeductStockRequest {
	if !p.IsSetReq() {
		return DeductStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeductStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeductStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeductStockResult struct {
	Success *product.DeductStockResponse
}

var DeductStockResult_Success_DEFAULT *product.DeductStockResponse

func (p *DeductStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeductStockResult) Unmarshal(in []byte) error {
	msg := new(product.DeductStockResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeductStockResult) GetSuccess() *product.DeductStockResponse {
	if !p.IsSetSuccess() {
		return DeductStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeductStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.DeductStockResponse)
}

func (p *DeductStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeductStockResult) GetResult() interface{} {
	return p.Success
}

func releaseStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.ReleaseStockRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).ReleaseStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ReleaseStockArgs:
		success, err := handler.(product.ProductService).ReleaseStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ReleaseStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newReleaseStockArgs() interface{} {
	return &ReleaseStockArgs{}
}

func newReleaseStockResult() interface{} {
	return &ReleaseStockResult{}
}

type ReleaseStockArgs struct {
	Req *product.ReleaseStockRequest
}

func (p *ReleaseStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ReleaseStockArgs) Unmarshal(in []byte) error {
	msg := new(product.ReleaseStockRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ReleaseStockArgs_Req_DEFAULT *product.ReleaseStockRequest

func (p *ReleaseStockArgs) GetReq() *product.ReleaseStockRequest {
	if !p.IsSetReq() {
		return ReleaseStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ReleaseStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ReleaseStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ReleaseStockResult struct {
	Success *product.ReleaseStockResponse
}

var ReleaseStockResult_Success_DEFAULT *product.ReleaseStockResponse

func (p *ReleaseStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ReleaseStockResult) Unmarshal(in []byte) error {
	msg := new(product.ReleaseStockResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ReleaseStockResult) GetSuccess() *product.ReleaseStockResponse {
	if !p.IsSetSuccess() {
		return ReleaseStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ReleaseStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.ReleaseStockResponse)
}

func (p *ReleaseStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ReleaseStockResult) GetResult() interface{} {
	return p.Success
}

func listCategoriesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.ListCategoriesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).ListCategories(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListCategoriesArgs:
		success, err := handler.(product.ProductService).ListCategories(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListCategoriesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListCategoriesArgs() interface{} {
	return &ListCategoriesArgs{}
}

func newListCategoriesResult() interface{} {
	return &ListCategoriesResult{}
}

type ListCategoriesArgs struct {
	Req *product.ListCategoriesRequest
}

func (p *ListCategoriesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListCategoriesArgs) Unmarshal(in []byte) error {
	msg := new(product.ListCategoriesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListCategoriesArgs_Req_DEFAULT *product.ListCategoriesRequest

func (p *ListCategoriesArgs) GetReq() *product.ListCategoriesRequest {
	if !p.IsSetReq() {
		return ListCategoriesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListCategoriesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListCategoriesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListCategoriesResult struct {
	Success *product.ListCategoriesResponse
}

var ListCategoriesResult_Success_DEFAULT *product.ListCategoriesResponse

func (p *ListCategoriesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListCategoriesResult) Unmarshal(in []byte) error {
	msg := new(product.ListCategoriesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListCategoriesResult) GetSuccess() *product.ListCategoriesResponse {
	if !p.IsSetSuccess() {
		return ListCategoriesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListCategoriesResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.ListCategoriesResponse)
}

func (p *ListCategoriesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListCategoriesResult) GetResult() interface{} {
	return p.Success
}

func listBrandsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.ListBrandsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).ListBrands(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListBrandsArgs:
		success, err := handler.(product.ProductService).ListBrands(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListBrandsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListBrandsArgs() interface{} {
	return &ListBrandsArgs{}
}

func newListBrandsResult() interface{} {
	return &ListBrandsResult{}
}

type ListBrandsArgs struct {
	Req *product.ListBrandsRequest
}

func (p *ListBrandsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListBrandsArgs) Unmarshal(in []byte) error {
	msg := new(product.ListBrandsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListBrandsArgs_Req_DEFAULT *product.ListBrandsRequest

func (p *ListBrandsArgs) GetReq() *product.ListBrandsRequest {
	if !p.IsSetReq() {
		return ListBrandsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListBrandsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListBrandsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListBrandsResult struct {
	Success *product.ListBrandsResponse
}

var ListBrandsResult_Success_DEFAULT *product.ListBrandsResponse

func (p *ListBrandsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListBrandsResult) Unmarshal(in []byte) error {
	msg := new(product.ListBrandsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListBrandsResult) GetSuccess() *product.ListBrandsResponse {
	if !p.IsSetSuccess() {
		return ListBrandsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListBrandsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.ListBrandsResponse)
}

func (p *ListBrandsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListBrandsResult) GetResult() interface{} {
	return p.Success
}

func searchProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.SearchProductsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).SearchProducts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchProductsArgs:
		success, err := handler.(product.ProductService).SearchProducts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchProductsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchProductsArgs() interface{} {
	return &SearchProductsArgs{}
}

func newSearchProductsResult() interface{} {
	return &SearchProductsResult{}
}

type SearchProductsArgs struct {
	Req *product.SearchProductsRequest
}

func (p *SearchProductsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchProductsArgs) Unmarshal(in []byte) error {
	msg := new(product.SearchProductsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchProductsArgs_Req_DEFAULT *product.SearchProductsRequest

func (p *SearchProductsArgs) GetReq() *product.SearchProductsRequest {
	if !p.IsSetReq() {
		return SearchProductsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchProductsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchProductsResult struct {
	Success *product.SearchProductsResponse
}

var SearchProductsResult_Success_DEFAULT *product.SearchProductsResponse

func (p *SearchProductsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchProductsResult) Unmarshal(in []byte) error {
	msg := new(product.SearchProductsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchProductsResult) GetSuccess() *product.SearchProductsResponse {
	if !p.IsSetSuccess() {
		return SearchProductsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.SearchProductsResponse)
}

func (p *SearchProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchProductsResult) GetResult() interface{} {
	return p.Success
}

func getHotProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.GetHotProductsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductService).GetHotProducts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetHotProductsArgs:
		success, err := handler.(product.ProductService).GetHotProducts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetHotProductsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetHotProductsArgs() interface{} {
	return &GetHotProductsArgs{}
}

func newGetHotProductsResult() interface{} {
	return &GetHotProductsResult{}
}

type GetHotProductsArgs struct {
	Req *product.GetHotProductsRequest
}

func (p *GetHotProductsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetHotProductsArgs) Unmarshal(in []byte) error {
	msg := new(product.GetHotProductsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetHotProductsArgs_Req_DEFAULT *product.GetHotProductsRequest

func (p *GetHotProductsArgs) GetReq() *product.GetHotProductsRequest {
	if !p.IsSetReq() {
		return GetHotProductsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetHotProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetHotProductsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetHotProductsResult struct {
	Success *product.GetHotProductsResponse
}

var GetHotProductsResult_Success_DEFAULT *product.GetHotProductsResponse

func (p *GetHotProductsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetHotProductsResult) Unmarshal(in []byte) error {
	msg := new(product.GetHotProductsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetHotProductsResult) GetSuccess() *product.GetHotProductsResponse {
	if !p.IsSetSuccess() {
		return GetHotProductsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetHotProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.GetHotProductsResponse)
}

func (p *GetHotProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetHotProductsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateProduct(ctx context.Context, Req *product.CreateProductRequest) (r *product.CreateProductResponse, err error) {
	var _args CreateProductArgs
	_args.Req = Req
	var _result CreateProductResult
	if err = p.c.Call(ctx, "CreateProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProduct(ctx context.Context, Req *product.UpdateProductRequest) (r *product.UpdateProductResponse, err error) {
	var _args UpdateProductArgs
	_args.Req = Req
	var _result UpdateProductResult
	if err = p.c.Call(ctx, "UpdateProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProductStatus(ctx context.Context, Req *product.UpdateProductStatusRequest) (r *product.UpdateProductStatusResponse, err error) {
	var _args UpdateProductStatusArgs
	_args.Req = Req
	var _result UpdateProductStatusResult
	if err = p.c.Call(ctx, "UpdateProductStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProductDetail(ctx context.Context, Req *product.GetProductDetailRequest) (r *product.GetProductDetailResponse, err error) {
	var _args GetProductDetailArgs
	_args.Req = Req
	var _result GetProductDetailResult
	if err = p.c.Call(ctx, "GetProductDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListProducts(ctx context.Context, Req *product.ListProductsRequest) (r *product.ListProductsResponse, err error) {
	var _args ListProductsArgs
	_args.Req = Req
	var _result ListProductsResult
	if err = p.c.Call(ctx, "ListProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProductsByIds(ctx context.Context, Req *product.GetProductsByIdsRequest) (r *product.GetProductsByIdsResponse, err error) {
	var _args GetProductsByIdsArgs
	_args.Req = Req
	var _result GetProductsByIdsResult
	if err = p.c.Call(ctx, "GetProductsByIds", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSkusByIds(ctx context.Context, Req *product.GetSkusByIdsRequest) (r *product.GetSkusByIdsResponse, err error) {
	var _args GetSkusByIdsArgs
	_args.Req = Req
	var _result GetSkusByIdsResult
	if err = p.c.Call(ctx, "GetSkusByIds", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchUpdateSku(ctx context.Context, Req *product.BatchUpdateSkuRequest) (r *product.BatchUpdateSkuResponse, err error) {
	var _args BatchUpdateSkuArgs
	_args.Req = Req
	var _result BatchUpdateSkuResult
	if err = p.c.Call(ctx, "BatchUpdateSku", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeductStock(ctx context.Context, Req *product.DeductStockRequest) (r *product.DeductStockResponse, err error) {
	var _args DeductStockArgs
	_args.Req = Req
	var _result DeductStockResult
	if err = p.c.Call(ctx, "DeductStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseStock(ctx context.Context, Req *product.ReleaseStockRequest) (r *product.ReleaseStockResponse, err error) {
	var _args ReleaseStockArgs
	_args.Req = Req
	var _result ReleaseStockResult
	if err = p.c.Call(ctx, "ReleaseStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCategories(ctx context.Context, Req *product.ListCategoriesRequest) (r *product.ListCategoriesResponse, err error) {
	var _args ListCategoriesArgs
	_args.Req = Req
	var _result ListCategoriesResult
	if err = p.c.Call(ctx, "ListCategories", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListBrands(ctx context.Context, Req *product.ListBrandsRequest) (r *product.ListBrandsResponse, err error) {
	var _args ListBrandsArgs
	_args.Req = Req
	var _result ListBrandsResult
	if err = p.c.Call(ctx, "ListBrands", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchProducts(ctx context.Context, Req *product.SearchProductsRequest) (r *product.SearchProductsResponse, err error) {
	var _args SearchProductsArgs
	_args.Req = Req
	var _result SearchProductsResult
	if err = p.c.Call(ctx, "SearchProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHotProducts(ctx context.Context, Req *product.GetHotProductsRequest) (r *product.GetHotProductsResponse, err error) {
	var _args GetHotProductsArgs
	_args.Req = Req
	var _result GetHotProductsResult
	if err = p.c.Call(ctx, "GetHotProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
