// Code generated by hertz generator.

package category

import (
	"github.com/PiaoAdmin/gomall/app/hertz_gateway/middleware"
	"github.com/PiaoAdmin/gomall/common/constant"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _category0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addcategoryMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.LoginCheck("_addcategoryMw"),
		middleware.PermissionCheck([]int32{constant.Merchant.RoleCode}),
	}
}
