// Code generated by hertz generator.

package home

import (
	"context"

	home "github.com/PiaoAdmin/pmall/app/api/biz/model/api/home"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// Home .
// @Summary      主页
// @Description  Home endpoint
// @Tags         Home
// @Success      200  {object}  response.Response{data=home.Empty}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @router / [GET]
func Home(ctx context.Context, c *app.RequestContext) {
	var err error
	var req home.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp := new(home.Empty)

	response.Success(c, resp)
}
