// Code generated by hertz generator.

package product

import (
	"context"

	product "github.com/PiaoAdmin/pmall/app/api/biz/model/api/product"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/product"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// GetHomeProducts .
// @Summary      获取首页商品列表
// @Description  Get home page product list (SPU) with pagination and filters
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        page        query     int32   false  "Page number"
// @Param        page_size   query     int32   false  "Page size"
// @Param        category_id query     int64   false  "Category ID"
// @Param        brand_id    query     int64   false  "Brand ID"
// @Success      200  {object}  response.Response{data=product.GetHomeProductsResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /products/home [GET]
func GetHomeProducts(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.GetHomeProductsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewGetHomeProductsService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}
	response.Success(c, resp)
}

// SearchProducts .
// @Summary      搜索商品
// @Description  Search products (SKU) with keyword, filters and sorting
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        page        query     int32   false  "Page number"
// @Param        page_size   query     int32   false  "Page size"
// @Param        keyword     query     string  false  "Search keyword"
// @Param        category_id query     int64   false  "Category ID"
// @Param        brand_id    query     int64   false  "Brand ID"
// @Param        min_price   query     int64   false  "Minimum price"
// @Param        max_price   query     int64   false  "Maximum price"
// @Param        sort_type   query     int32   false  "Sort type (0:default, 1:price asc, 2:price desc, 3:sales)"
// @Success      200  {object}  response.Response{data=product.SearchProductsResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /products/search [GET]
func SearchProducts(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.SearchProductsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewSearchProductsService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// GetProductDetail .
// @Summary      获取商品详情
// @Description  Get product detail including SPU, SKUs, category, brand and detail info
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        spu_id  path      int64  true  "Product SPU ID"
// @Success      200  {object}  response.Response{data=product.GetProductDetailResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /products/{spu_id} [GET]
func GetProductDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.GetProductDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewGetProductDetailService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// ListCategories .
// @Summary      获取分类列表
// @Description  Get category list with optional parent filter
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        parent_id  query     int64  false  "Parent category ID (0 for root categories)"
// @Success      200  {object}  response.Response{data=product.ListCategoriesResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /categories [GET]
func ListCategories(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.ListCategoriesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewListCategoriesService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// ListBrands .
// @Summary      获取品牌列表
// @Description  Get brand list with pagination
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        page       query     int32  false  "Page number"
// @Param        page_size  query     int32  false  "Page size"
// @Success      200  {object}  response.Response{data=product.ListBrandsResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /brands [GET]
func ListBrands(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.ListBrandsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewListBrandsService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// CreateProduct .
// @Summary      创建商品
// @Description  Create a new product with SPU, SKUs and detail info (Admin only)
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        req  body      product.CreateProductRequest  true  "Create Product Request"
// @Success      200  {object}  response.Response{data=product.CreateProductResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /admin/products [POST]
func CreateProduct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.CreateProductRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.Errorf("CreateProduct BindAndValidate error: %v", err)
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewCreateProductService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// BatchUpdateSku .
// @Summary      批量更新SKU
// @Description  Batch update SKU price and stock (Admin only)
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        req  body      product.BatchUpdateSkuRequest  true  "Batch Update SKU Request"
// @Success      200  {object}  response.Response{data=product.BatchUpdateSkuResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /admin/skus/batch [POST]
func BatchUpdateSku(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.BatchUpdateSkuRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewBatchUpdateSkuService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// GetHotProducts .
// @Summary      获取热门商品列表
// @Description  Get hot products list sorted by sales count
// @Tags         Product
// @Accept       json
// @Produce      json
// @Param        limit  query     int32   false  "Limit (default 10, max 100)"
// @Success      200  {object}  response.Response{data=product.GetHotProductsResponse}
// @Failure      400  {object}  response.Response{data=string}  "Bad Request"
// @Failure      500  {object}  response.Response{data=string}  "Internal Server Error"
// @Router       /products/hot [GET]
func GetHotProducts(ctx context.Context, c *app.RequestContext) {
	var err error
	var req product.GetHotProductsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewGetHotProductsService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
