// Code generated by Kitex v0.15.4. DO NOT EDIT.

package product

import (
	"context"

	"github.com/cloudwego/prutal"
)

// 消息结构定义 (Messages)
// SPU 模型
type ProductSPU struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BrandId       uint64 `protobuf:"varint,2,opt,name=brand_id" json:"brand_id,omitempty"`
	CategoryId    uint64 `protobuf:"varint,3,opt,name=category_id" json:"category_id,omitempty"`
	Name          string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	SubTitle      string `protobuf:"bytes,5,opt,name=sub_title" json:"sub_title,omitempty"`
	MainImage     string `protobuf:"bytes,6,opt,name=main_image" json:"main_image,omitempty"`
	PublishStatus int32  `protobuf:"varint,7,opt,name=publish_status" json:"publish_status,omitempty"`
	VerifyStatus  int32  `protobuf:"varint,8,opt,name=verify_status" json:"verify_status,omitempty"`
	LowPrice      string `protobuf:"bytes,9,opt,name=low_price" json:"low_price,omitempty"` // Decimal 推荐用 string 传输以防精度丢失
	HighPrice     string `protobuf:"bytes,10,opt,name=high_price" json:"high_price,omitempty"`
	SaleCount     int32  `protobuf:"varint,11,opt,name=sale_count" json:"sale_count,omitempty"`
	Sort          int32  `protobuf:"varint,12,opt,name=sort" json:"sort,omitempty"`
	ServiceBits   int64  `protobuf:"varint,13,opt,name=service_bits" json:"service_bits,omitempty"`
	Version       int32  `protobuf:"varint,14,opt,name=version" json:"version,omitempty"`
}

func (x *ProductSPU) Reset() { *x = ProductSPU{} }

func (x *ProductSPU) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProductSPU) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProductSPU) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductSPU) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ProductSPU) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductSPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSPU) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *ProductSPU) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *ProductSPU) GetPublishStatus() int32 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

func (x *ProductSPU) GetVerifyStatus() int32 {
	if x != nil {
		return x.VerifyStatus
	}
	return 0
}

func (x *ProductSPU) GetLowPrice() string {
	if x != nil {
		return x.LowPrice
	}
	return ""
}

func (x *ProductSPU) GetHighPrice() string {
	if x != nil {
		return x.HighPrice
	}
	return ""
}

func (x *ProductSPU) GetSaleCount() int32 {
	if x != nil {
		return x.SaleCount
	}
	return 0
}

func (x *ProductSPU) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductSPU) GetServiceBits() int64 {
	if x != nil {
		return x.ServiceBits
	}
	return 0
}

func (x *ProductSPU) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// SPU detail
type ProductDetail struct {
	Description   string   `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`         // 富文本描述
	Images        []string `protobuf:"bytes,2,rep,name=images" json:"images,omitempty"`                   // 商品图
	Videos        []string `protobuf:"bytes,3,rep,name=videos" json:"videos,omitempty"`                   // 商品视频
	MarketTagJson string   `protobuf:"bytes,4,opt,name=market_tag_json" json:"market_tag_json,omitempty"` // 营销标签 JSON 字符串
	TechTagJson   string   `protobuf:"bytes,5,opt,name=tech_tag_json" json:"tech_tag_json,omitempty"`     // 技术参数 JSON 字符串
	FaqJson       string   `protobuf:"bytes,6,opt,name=faq_json" json:"faq_json,omitempty"`               // 常见问题 JSON 字符串
}

func (x *ProductDetail) Reset() { *x = ProductDetail{} }

func (x *ProductDetail) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProductDetail) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProductDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductDetail) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductDetail) GetVideos() []string {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ProductDetail) GetMarketTagJson() string {
	if x != nil {
		return x.MarketTagJson
	}
	return ""
}

func (x *ProductDetail) GetTechTagJson() string {
	if x != nil {
		return x.TechTagJson
	}
	return ""
}

func (x *ProductDetail) GetFaqJson() string {
	if x != nil {
		return x.FaqJson
	}
	return ""
}

// SKU 模型
type ProductSKU struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SpuId       uint64 `protobuf:"varint,2,opt,name=spu_id" json:"spu_id,omitempty"`
	SkuCode     string `protobuf:"bytes,3,opt,name=sku_code" json:"sku_code,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	SubTitle    string `protobuf:"bytes,5,opt,name=sub_title" json:"sub_title,omitempty"`
	MainImage   string `protobuf:"bytes,6,opt,name=main_image" json:"main_image,omitempty"`
	Price       string `protobuf:"bytes,7,opt,name=price" json:"price,omitempty"`
	MarketPrice string `protobuf:"bytes,8,opt,name=market_price" json:"market_price,omitempty"`
	Stock       int32  `protobuf:"varint,9,opt,name=stock" json:"stock,omitempty"`
	LockStock   int32  `protobuf:"varint,10,opt,name=lock_stock" json:"lock_stock,omitempty"`
	SkuSpecData string `protobuf:"bytes,11,opt,name=sku_spec_data" json:"sku_spec_data,omitempty"` // JSON 字符串
	Version     int32  `protobuf:"varint,12,opt,name=version" json:"version,omitempty"`
}

func (x *ProductSKU) Reset() { *x = ProductSKU{} }

func (x *ProductSKU) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProductSKU) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProductSKU) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductSKU) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *ProductSKU) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *ProductSKU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSKU) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *ProductSKU) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *ProductSKU) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ProductSKU) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *ProductSKU) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductSKU) GetLockStock() int32 {
	if x != nil {
		return x.LockStock
	}
	return 0
}

func (x *ProductSKU) GetSkuSpecData() string {
	if x != nil {
		return x.SkuSpecData
	}
	return ""
}

func (x *ProductSKU) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 分类模型
type Category struct {
	Id       uint64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ParentId uint64      `protobuf:"varint,2,opt,name=parent_id" json:"parent_id,omitempty"`
	Name     string      `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Level    int32       `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
	Icon     string      `protobuf:"bytes,5,opt,name=icon" json:"icon,omitempty"`
	Unit     string      `protobuf:"bytes,6,opt,name=unit" json:"unit,omitempty"`
	Sort     int32       `protobuf:"varint,7,opt,name=sort" json:"sort,omitempty"`
	Children []*Category `protobuf:"bytes,8,rep,name=children" json:"children,omitempty"` // 树形结构返回时用
}

func (x *Category) Reset() { *x = Category{} }

func (x *Category) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Category) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Category) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Category) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Category) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Category) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Category) GetChildren() []*Category {
	if x != nil {
		return x.Children
	}
	return nil
}

// 品牌模型
type Brand struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	FirstLetter string `protobuf:"bytes,3,opt,name=first_letter" json:"first_letter,omitempty"`
	Logo        string `protobuf:"bytes,4,opt,name=logo" json:"logo,omitempty"`
	Sort        int32  `protobuf:"varint,5,opt,name=sort" json:"sort,omitempty"`
}

func (x *Brand) Reset() { *x = Brand{} }

func (x *Brand) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Brand) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Brand) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetFirstLetter() string {
	if x != nil {
		return x.FirstLetter
	}
	return ""
}

func (x *Brand) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Brand) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// --- 请求与响应定义 ---
// 1. CreateProduct
type CreateProductRequest struct {
	Spu    *ProductSPU    `protobuf:"bytes,1,opt,name=spu" json:"spu,omitempty"`       // 基础信息
	Skus   []*ProductSKU  `protobuf:"bytes,2,rep,name=skus" json:"skus,omitempty"`     // 对应的规格列表
	Detail *ProductDetail `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"` // 详细信息
}

func (x *CreateProductRequest) Reset() { *x = CreateProductRequest{} }

func (x *CreateProductRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateProductRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateProductRequest) GetSpu() *ProductSPU {
	if x != nil {
		return x.Spu
	}
	return nil
}

func (x *CreateProductRequest) GetSkus() []*ProductSKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *CreateProductRequest) GetDetail() *ProductDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type CreateProductResponse struct {
	SpuId uint64 `protobuf:"varint,1,opt,name=spu_id" json:"spu_id,omitempty"`
}

func (x *CreateProductResponse) Reset() { *x = CreateProductResponse{} }

func (x *CreateProductResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateProductResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateProductResponse) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

// 2. UpdateProduct
type UpdateProductRequest struct {
	Spu    *ProductSPU    `protobuf:"bytes,1,opt,name=spu" json:"spu,omitempty"`       // 只更新非空字段
	Detail *ProductDetail `protobuf:"bytes,2,opt,name=detail" json:"detail,omitempty"` // 详细信息
}

func (x *UpdateProductRequest) Reset() { *x = UpdateProductRequest{} }

func (x *UpdateProductRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateProductRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductRequest) GetSpu() *ProductSPU {
	if x != nil {
		return x.Spu
	}
	return nil
}

func (x *UpdateProductRequest) GetDetail() *ProductDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type UpdateProductResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *UpdateProductResponse) Reset() { *x = UpdateProductResponse{} }

func (x *UpdateProductResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UpdateProductResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 3. UpdateProductStatus
type UpdateProductStatusRequest struct {
	Ids           []uint64 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
	PublishStatus int32    `protobuf:"varint,2,opt,name=publish_status" json:"publish_status,omitempty"` // 0:不变更, 1:上架, 2:下架
	VerifyStatus  int32    `protobuf:"varint,3,opt,name=verify_status" json:"verify_status,omitempty"`   // 0:不变更, 1:审核通过...
}

func (x *UpdateProductStatusRequest) Reset() { *x = UpdateProductStatusRequest{} }

func (x *UpdateProductStatusRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UpdateProductStatusRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductStatusRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateProductStatusRequest) GetPublishStatus() int32 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

func (x *UpdateProductStatusRequest) GetVerifyStatus() int32 {
	if x != nil {
		return x.VerifyStatus
	}
	return 0
}

type UpdateProductStatusResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *UpdateProductStatusResponse) Reset() { *x = UpdateProductStatusResponse{} }

func (x *UpdateProductStatusResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UpdateProductStatusResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 4. GetProductDetail
type GetProductDetailRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetProductDetailRequest) Reset() { *x = GetProductDetailRequest{} }

func (x *GetProductDetailRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetProductDetailRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductDetailResponse struct {
	Spu      *ProductSPU    `protobuf:"bytes,1,opt,name=spu" json:"spu,omitempty"`
	Skus     []*ProductSKU  `protobuf:"bytes,2,rep,name=skus" json:"skus,omitempty"`
	Category *Category      `protobuf:"bytes,3,opt,name=category" json:"category,omitempty"`
	Brand    *Brand         `protobuf:"bytes,4,opt,name=brand" json:"brand,omitempty"`
	Detail   *ProductDetail `protobuf:"bytes,5,opt,name=detail" json:"detail,omitempty"`
}

func (x *GetProductDetailResponse) Reset() { *x = GetProductDetailResponse{} }

func (x *GetProductDetailResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetProductDetailResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductDetailResponse) GetSpu() *ProductSPU {
	if x != nil {
		return x.Spu
	}
	return nil
}

func (x *GetProductDetailResponse) GetSkus() []*ProductSKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *GetProductDetailResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *GetProductDetailResponse) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *GetProductDetailResponse) GetDetail() *ProductDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// 5. ListProducts (后台筛选)
type ListProductsRequest struct {
	Page          int32  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize      int32  `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
	Keyword       string `protobuf:"bytes,3,opt,name=keyword" json:"keyword,omitempty"`
	CategoryId    uint64 `protobuf:"varint,4,opt,name=category_id" json:"category_id,omitempty"`
	BrandId       uint64 `protobuf:"varint,5,opt,name=brand_id" json:"brand_id,omitempty"`
	PublishStatus int32  `protobuf:"varint,6,opt,name=publish_status" json:"publish_status,omitempty"` // -1表示全部
	VerifyStatus  int32  `protobuf:"varint,7,opt,name=verify_status" json:"verify_status,omitempty"`
}

func (x *ListProductsRequest) Reset() { *x = ListProductsRequest{} }

func (x *ListProductsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListProductsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListProductsRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListProductsRequest) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ListProductsRequest) GetPublishStatus() int32 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

func (x *ListProductsRequest) GetVerifyStatus() int32 {
	if x != nil {
		return x.VerifyStatus
	}
	return 0
}

type ListProductsResponse struct {
	List  []*ProductSPU `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Total int64         `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListProductsResponse) Reset() { *x = ListProductsResponse{} }

func (x *ListProductsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListProductsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListProductsResponse) GetList() []*ProductSPU {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 6. GetProductsByIds
type GetProductsByIdsRequest struct {
	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (x *GetProductsByIdsRequest) Reset() { *x = GetProductsByIdsRequest{} }

func (x *GetProductsByIdsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetProductsByIdsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductsByIdsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetProductsByIdsResponse struct {
	Products map[uint64]*ProductSPU `protobuf:"bytes,1,rep,name=products" json:"products,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // ID -> SPU 映射
}

func (x *GetProductsByIdsResponse) Reset() { *x = GetProductsByIdsResponse{} }

func (x *GetProductsByIdsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetProductsByIdsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductsByIdsResponse) GetProducts() map[uint64]*ProductSPU {
	if x != nil {
		return x.Products
	}
	return nil
}

// 7. GetSkusByIds (批量获取 SKU 详情)
type GetSkusByIdsRequest struct {
	SkuIds []uint64 `protobuf:"varint,1,rep,packed,name=sku_ids" json:"sku_ids,omitempty"`
}

func (x *GetSkusByIdsRequest) Reset() { *x = GetSkusByIdsRequest{} }

func (x *GetSkusByIdsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSkusByIdsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSkusByIdsRequest) GetSkuIds() []uint64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type GetSkusByIdsResponse struct {
	Skus map[uint64]*ProductSKU `protobuf:"bytes,1,rep,name=skus" json:"skus,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *GetSkusByIdsResponse) Reset() { *x = GetSkusByIdsResponse{} }

func (x *GetSkusByIdsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSkusByIdsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSkusByIdsResponse) GetSkus() map[uint64]*ProductSKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

// 8. BatchUpdateSku
type BatchUpdateSkuRequest struct {
	Skus []*ProductSKU `protobuf:"bytes,1,rep,name=skus" json:"skus,omitempty"` // 根据 sku_id 更新 price/stock
}

func (x *BatchUpdateSkuRequest) Reset() { *x = BatchUpdateSkuRequest{} }

func (x *BatchUpdateSkuRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchUpdateSkuRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchUpdateSkuRequest) GetSkus() []*ProductSKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

type BatchUpdateSkuResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *BatchUpdateSkuResponse) Reset() { *x = BatchUpdateSkuResponse{} }

func (x *BatchUpdateSkuResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *BatchUpdateSkuResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BatchUpdateSkuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 9. DeductStock (核心)
type SkuDeductItem struct {
	SkuId uint64 `protobuf:"varint,1,opt,name=sku_id" json:"sku_id,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (x *SkuDeductItem) Reset() { *x = SkuDeductItem{} }

func (x *SkuDeductItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SkuDeductItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SkuDeductItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *SkuDeductItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeductStockRequest struct {
	OrderSn string           `protobuf:"bytes,1,opt,name=order_sn" json:"order_sn,omitempty"` // 订单号，用于幂等性
	Items   []*SkuDeductItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *DeductStockRequest) Reset() { *x = DeductStockRequest{} }

func (x *DeductStockRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeductStockRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeductStockRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *DeductStockRequest) GetItems() []*SkuDeductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeductStockResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *DeductStockResponse) Reset() { *x = DeductStockResponse{} }

func (x *DeductStockResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeductStockResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeductStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 10. ReleaseStock
type ReleaseStockRequest struct {
	OrderSn string           `protobuf:"bytes,1,opt,name=order_sn" json:"order_sn,omitempty"`
	Items   []*SkuDeductItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *ReleaseStockRequest) Reset() { *x = ReleaseStockRequest{} }

func (x *ReleaseStockRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReleaseStockRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReleaseStockRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ReleaseStockRequest) GetItems() []*SkuDeductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseStockResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *ReleaseStockResponse) Reset() { *x = ReleaseStockResponse{} }

func (x *ReleaseStockResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReleaseStockResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReleaseStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 11. ListCategories
type ListCategoriesRequest struct {
	ParentId uint64 `protobuf:"varint,1,opt,name=parent_id" json:"parent_id,omitempty"` // 0 获取所有一级，或者 -1 获取全树
}

func (x *ListCategoriesRequest) Reset() { *x = ListCategoriesRequest{} }

func (x *ListCategoriesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListCategoriesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListCategoriesRequest) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ListCategoriesResponse struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (x *ListCategoriesResponse) Reset() { *x = ListCategoriesResponse{} }

func (x *ListCategoriesResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListCategoriesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// 12. ListBrands
type ListBrandsRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListBrandsRequest) Reset() { *x = ListBrandsRequest{} }

func (x *ListBrandsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListBrandsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListBrandsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBrandsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBrandsResponse struct {
	Brands []*Brand `protobuf:"bytes,1,rep,name=brands" json:"brands,omitempty"`
	Total  int64    `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListBrandsResponse) Reset() { *x = ListBrandsResponse{} }

func (x *ListBrandsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListBrandsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListBrandsResponse) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *ListBrandsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 13. SearchProducts (C端商品搜索，返回可购买的 SKU)
type SearchProductsRequest struct {
	Page       int32  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize   int32  `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
	Keyword    string `protobuf:"bytes,3,opt,name=keyword" json:"keyword,omitempty"`          // 搜索关键词
	CategoryId uint64 `protobuf:"varint,4,opt,name=category_id" json:"category_id,omitempty"` // 分类筛选
	BrandId    uint64 `protobuf:"varint,5,opt,name=brand_id" json:"brand_id,omitempty"`       // 品牌筛选
	MinPrice   string `protobuf:"bytes,6,opt,name=min_price" json:"min_price,omitempty"`      // 最低价格
	MaxPrice   string `protobuf:"bytes,7,opt,name=max_price" json:"max_price,omitempty"`      // 最高价格
	SortType   int32  `protobuf:"varint,8,opt,name=sort_type" json:"sort_type,omitempty"`     // 排序: 0-综合, 1-价格升序, 2-价格降序, 3-销量降序
}

func (x *SearchProductsRequest) Reset() { *x = SearchProductsRequest{} }

func (x *SearchProductsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SearchProductsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchProductsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchProductsRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SearchProductsRequest) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SearchProductsRequest) GetMinPrice() string {
	if x != nil {
		return x.MinPrice
	}
	return ""
}

func (x *SearchProductsRequest) GetMaxPrice() string {
	if x != nil {
		return x.MaxPrice
	}
	return ""
}

func (x *SearchProductsRequest) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

type SearchProductsResponse struct {
	List  []*SearchProductItem `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Total int64                `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *SearchProductsResponse) Reset() { *x = SearchProductsResponse{} }

func (x *SearchProductsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SearchProductsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchProductsResponse) GetList() []*SearchProductItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 搜索结果项：SKU + 关联的 SPU 基本信息
type SearchProductItem struct {
	Sku          *ProductSKU `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`                        // SKU 详细信息
	SpuId        uint64      `protobuf:"varint,2,opt,name=spu_id" json:"spu_id,omitempty"`                 // 关联的 SPU ID
	SpuName      string      `protobuf:"bytes,3,opt,name=spu_name" json:"spu_name,omitempty"`              // SPU 名称
	BrandId      uint64      `protobuf:"varint,4,opt,name=brand_id" json:"brand_id,omitempty"`             // 品牌 ID
	BrandName    string      `protobuf:"bytes,5,opt,name=brand_name" json:"brand_name,omitempty"`          // 品牌名称
	CategoryId   uint64      `protobuf:"varint,6,opt,name=category_id" json:"category_id,omitempty"`       // 分类 ID
	CategoryName string      `protobuf:"bytes,7,opt,name=category_name" json:"category_name,omitempty"`    // 分类名称
	SpuSaleCount int32       `protobuf:"varint,8,opt,name=spu_sale_count" json:"spu_sale_count,omitempty"` // SPU 总销量
}

func (x *SearchProductItem) Reset() { *x = SearchProductItem{} }

func (x *SearchProductItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchProductItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchProductItem) GetSku() *ProductSKU {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *SearchProductItem) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *SearchProductItem) GetSpuName() string {
	if x != nil {
		return x.SpuName
	}
	return ""
}

func (x *SearchProductItem) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SearchProductItem) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *SearchProductItem) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SearchProductItem) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *SearchProductItem) GetSpuSaleCount() int32 {
	if x != nil {
		return x.SpuSaleCount
	}
	return 0
}

type ProductService interface {
	CreateProduct(ctx context.Context, req *CreateProductRequest) (res *CreateProductResponse, err error)
	UpdateProduct(ctx context.Context, req *UpdateProductRequest) (res *UpdateProductResponse, err error)
	UpdateProductStatus(ctx context.Context, req *UpdateProductStatusRequest) (res *UpdateProductStatusResponse, err error)
	GetProductDetail(ctx context.Context, req *GetProductDetailRequest) (res *GetProductDetailResponse, err error)
	ListProducts(ctx context.Context, req *ListProductsRequest) (res *ListProductsResponse, err error)
	GetProductsByIds(ctx context.Context, req *GetProductsByIdsRequest) (res *GetProductsByIdsResponse, err error)
	GetSkusByIds(ctx context.Context, req *GetSkusByIdsRequest) (res *GetSkusByIdsResponse, err error)
	BatchUpdateSku(ctx context.Context, req *BatchUpdateSkuRequest) (res *BatchUpdateSkuResponse, err error)
	DeductStock(ctx context.Context, req *DeductStockRequest) (res *DeductStockResponse, err error)
	ReleaseStock(ctx context.Context, req *ReleaseStockRequest) (res *ReleaseStockResponse, err error)
	ListCategories(ctx context.Context, req *ListCategoriesRequest) (res *ListCategoriesResponse, err error)
	ListBrands(ctx context.Context, req *ListBrandsRequest) (res *ListBrandsResponse, err error)
	SearchProducts(ctx context.Context, req *SearchProductsRequest) (res *SearchProductsResponse, err error)
}
