// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: checkout_api.proto

package checkout

import (
	_ "github.com/PiaoAdmin/pmall/app/api/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
	StreetAddress string `protobuf:"bytes,2,opt,name=street_address,json=streetAddress,proto3" form:"street_address" json:"street_address,omitempty" query:"street_address"`
	City          string `protobuf:"bytes,3,opt,name=city,proto3" form:"city" json:"city,omitempty" query:"city"`
	ZipCode       int32  `protobuf:"varint,4,opt,name=zip_code,json=zipCode,proto3" form:"zip_code" json:"zip_code,omitempty" query:"zip_code"`
}

func (x *AddressDTO) Reset() {
	*x = AddressDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkout_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressDTO) ProtoMessage() {}

func (x *AddressDTO) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressDTO.ProtoReflect.Descriptor instead.
func (*AddressDTO) Descriptor() ([]byte, []int) {
	return file_checkout_api_proto_rawDescGZIP(), []int{0}
}

func (x *AddressDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddressDTO) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *AddressDTO) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressDTO) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

type CheckoutItemDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId       uint64 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" form:"sku_id" json:"sku_id,omitempty" query:"sku_id"`
	Quantity    int32  `protobuf:"varint,2,opt,name=quantity,proto3" form:"quantity" json:"quantity,omitempty" query:"quantity"`
	SkuName     string `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" form:"sku_name" json:"sku_name,omitempty" query:"sku_name"`
	SkuImage    string `protobuf:"bytes,4,opt,name=sku_image,json=skuImage,proto3" form:"sku_image" json:"sku_image,omitempty" query:"sku_image"`
	Price       string `protobuf:"bytes,5,opt,name=price,proto3" form:"price" json:"price,omitempty" query:"price"`
	MarketPrice string `protobuf:"bytes,6,opt,name=market_price,json=marketPrice,proto3" form:"market_price" json:"market_price,omitempty" query:"market_price"`
	SpuId       uint64 `protobuf:"varint,7,opt,name=spu_id,json=spuId,proto3" form:"spu_id" json:"spu_id,omitempty" query:"spu_id"`
	SkuSpecData string `protobuf:"bytes,8,opt,name=sku_spec_data,json=skuSpecData,proto3" form:"sku_spec_data" json:"sku_spec_data,omitempty" query:"sku_spec_data"`
}

func (x *CheckoutItemDTO) Reset() {
	*x = CheckoutItemDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkout_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutItemDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutItemDTO) ProtoMessage() {}

func (x *CheckoutItemDTO) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutItemDTO.ProtoReflect.Descriptor instead.
func (*CheckoutItemDTO) Descriptor() ([]byte, []int) {
	return file_checkout_api_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutItemDTO) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CheckoutItemDTO) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckoutItemDTO) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CheckoutItemDTO) GetSkuImage() string {
	if x != nil {
		return x.SkuImage
	}
	return ""
}

func (x *CheckoutItemDTO) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CheckoutItemDTO) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *CheckoutItemDTO) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CheckoutItemDTO) GetSkuSpecData() string {
	if x != nil {
		return x.SkuSpecData
	}
	return ""
}

type CheckoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShippingAddress *AddressDTO `protobuf:"bytes,1,opt,name=shipping_address,json=shippingAddress,proto3" form:"shipping_address" json:"shipping_address,omitempty"`
}

func (x *CheckoutReq) Reset() {
	*x = CheckoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkout_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutReq) ProtoMessage() {}

func (x *CheckoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutReq.ProtoReflect.Descriptor instead.
func (*CheckoutReq) Descriptor() ([]byte, []int) {
	return file_checkout_api_proto_rawDescGZIP(), []int{2}
}

func (x *CheckoutReq) GetShippingAddress() *AddressDTO {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

type CheckoutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string             `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" form:"order_id" json:"order_id,omitempty" query:"order_id"`
	TotalAmount string             `protobuf:"bytes,2,opt,name=total_amount,json=totalAmount,proto3" form:"total_amount" json:"total_amount,omitempty" query:"total_amount"`
	Items       []*CheckoutItemDTO `protobuf:"bytes,3,rep,name=items,proto3" form:"items" json:"items,omitempty" query:"items"`
}

func (x *CheckoutResp) Reset() {
	*x = CheckoutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkout_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResp) ProtoMessage() {}

func (x *CheckoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResp.ProtoReflect.Descriptor instead.
func (*CheckoutResp) Descriptor() ([]byte, []int) {
	return file_checkout_api_proto_rawDescGZIP(), []int{3}
}

func (x *CheckoutResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CheckoutResp) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CheckoutResp) GetItems() []*CheckoutItemDTO {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_checkout_api_proto protoreflect.FileDescriptor

var file_checkout_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x76, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x54, 0x4f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x72,
	0x65, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x19,
	0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x0f, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x54, 0x4f, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73,
	0x6b, 0x75, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x6b, 0x75, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x6b, 0x75, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6b, 0x75, 0x5f,
	0x73, 0x70, 0x65, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x6b, 0x75, 0x53, 0x70, 0x65, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x0b,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x5d, 0x0a, 0x10, 0x73,
	0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x44, 0x54, 0x4f, 0x42, 0x14, 0xca, 0xbb, 0x18, 0x10, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0f, 0x73, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x54, 0x4f, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x32, 0x6b, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x12, 0x1d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x0d, 0xd2, 0xc1, 0x18, 0x09, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x42,
	0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x69,
	0x61, 0x6f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x70, 0x6d, 0x61, 0x6c, 0x6c, 0x2f, 0x61, 0x70,
	0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_checkout_api_proto_rawDescOnce sync.Once
	file_checkout_api_proto_rawDescData = file_checkout_api_proto_rawDesc
)

func file_checkout_api_proto_rawDescGZIP() []byte {
	file_checkout_api_proto_rawDescOnce.Do(func() {
		file_checkout_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_checkout_api_proto_rawDescData)
	})
	return file_checkout_api_proto_rawDescData
}

var file_checkout_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_checkout_api_proto_goTypes = []interface{}{
	(*AddressDTO)(nil),      // 0: gateway.checkout.AddressDTO
	(*CheckoutItemDTO)(nil), // 1: gateway.checkout.CheckoutItemDTO
	(*CheckoutReq)(nil),     // 2: gateway.checkout.CheckoutReq
	(*CheckoutResp)(nil),    // 3: gateway.checkout.CheckoutResp
}
var file_checkout_api_proto_depIdxs = []int32{
	0, // 0: gateway.checkout.CheckoutReq.shipping_address:type_name -> gateway.checkout.AddressDTO
	1, // 1: gateway.checkout.CheckoutResp.items:type_name -> gateway.checkout.CheckoutItemDTO
	2, // 2: gateway.checkout.CheckoutService.Checkout:input_type -> gateway.checkout.CheckoutReq
	3, // 3: gateway.checkout.CheckoutService.Checkout:output_type -> gateway.checkout.CheckoutResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_checkout_api_proto_init() }
func file_checkout_api_proto_init() {
	if File_checkout_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_checkout_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkout_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutItemDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkout_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkout_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checkout_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_api_proto_goTypes,
		DependencyIndexes: file_checkout_api_proto_depIdxs,
		MessageInfos:      file_checkout_api_proto_msgTypes,
	}.Build()
	File_checkout_api_proto = out.File
	file_checkout_api_proto_rawDesc = nil
	file_checkout_api_proto_goTypes = nil
	file_checkout_api_proto_depIdxs = nil
}
