// Code generated by Kitex v0.15.4. DO NOT EDIT.

package cartservice

import (
	"context"
	"errors"
	cart "github.com/PiaoAdmin/pmall/rpc_gen/cart"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddToCart": kitex.NewMethodInfo(
		addToCartHandler,
		newAddToCartArgs,
		newAddToCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RemoveFromCart": kitex.NewMethodInfo(
		removeFromCartHandler,
		newRemoveFromCartArgs,
		newRemoveFromCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCartDetails": kitex.NewMethodInfo(
		getCartDetailsHandler,
		newGetCartDetailsArgs,
		newGetCartDetailsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ClearCart": kitex.NewMethodInfo(
		clearCartHandler,
		newClearCartArgs,
		newClearCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	cartServiceServiceInfo                = NewServiceInfo()
	cartServiceServiceInfoForClient       = NewServiceInfoForClient()
	cartServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cartServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CartService"
	handlerType := (*cart.CartService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "cart",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func addToCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(cart.AddToCartRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cart.CartService).AddToCart(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddToCartArgs:
		success, err := handler.(cart.CartService).AddToCart(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddToCartResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddToCartArgs() interface{} {
	return &AddToCartArgs{}
}

func newAddToCartResult() interface{} {
	return &AddToCartResult{}
}

type AddToCartArgs struct {
	Req *cart.AddToCartRequest
}

func (p *AddToCartArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddToCartArgs) Unmarshal(in []byte) error {
	msg := new(cart.AddToCartRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddToCartArgs_Req_DEFAULT *cart.AddToCartRequest

func (p *AddToCartArgs) GetReq() *cart.AddToCartRequest {
	if !p.IsSetReq() {
		return AddToCartArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddToCartArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddToCartArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddToCartResult struct {
	Success *cart.AddToCartResponse
}

var AddToCartResult_Success_DEFAULT *cart.AddToCartResponse

func (p *AddToCartResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddToCartResult) Unmarshal(in []byte) error {
	msg := new(cart.AddToCartResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddToCartResult) GetSuccess() *cart.AddToCartResponse {
	if !p.IsSetSuccess() {
		return AddToCartResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddToCartResult) SetSuccess(x interface{}) {
	p.Success = x.(*cart.AddToCartResponse)
}

func (p *AddToCartResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddToCartResult) GetResult() interface{} {
	return p.Success
}

func removeFromCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(cart.RemoveFromCartRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cart.CartService).RemoveFromCart(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RemoveFromCartArgs:
		success, err := handler.(cart.CartService).RemoveFromCart(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RemoveFromCartResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRemoveFromCartArgs() interface{} {
	return &RemoveFromCartArgs{}
}

func newRemoveFromCartResult() interface{} {
	return &RemoveFromCartResult{}
}

type RemoveFromCartArgs struct {
	Req *cart.RemoveFromCartRequest
}

func (p *RemoveFromCartArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RemoveFromCartArgs) Unmarshal(in []byte) error {
	msg := new(cart.RemoveFromCartRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RemoveFromCartArgs_Req_DEFAULT *cart.RemoveFromCartRequest

func (p *RemoveFromCartArgs) GetReq() *cart.RemoveFromCartRequest {
	if !p.IsSetReq() {
		return RemoveFromCartArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RemoveFromCartArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RemoveFromCartArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RemoveFromCartResult struct {
	Success *cart.RemoveFromCartResponse
}

var RemoveFromCartResult_Success_DEFAULT *cart.RemoveFromCartResponse

func (p *RemoveFromCartResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RemoveFromCartResult) Unmarshal(in []byte) error {
	msg := new(cart.RemoveFromCartResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RemoveFromCartResult) GetSuccess() *cart.RemoveFromCartResponse {
	if !p.IsSetSuccess() {
		return RemoveFromCartResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RemoveFromCartResult) SetSuccess(x interface{}) {
	p.Success = x.(*cart.RemoveFromCartResponse)
}

func (p *RemoveFromCartResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RemoveFromCartResult) GetResult() interface{} {
	return p.Success
}

func getCartDetailsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(cart.GetCartDetailsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cart.CartService).GetCartDetails(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCartDetailsArgs:
		success, err := handler.(cart.CartService).GetCartDetails(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCartDetailsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCartDetailsArgs() interface{} {
	return &GetCartDetailsArgs{}
}

func newGetCartDetailsResult() interface{} {
	return &GetCartDetailsResult{}
}

type GetCartDetailsArgs struct {
	Req *cart.GetCartDetailsRequest
}

func (p *GetCartDetailsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCartDetailsArgs) Unmarshal(in []byte) error {
	msg := new(cart.GetCartDetailsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCartDetailsArgs_Req_DEFAULT *cart.GetCartDetailsRequest

func (p *GetCartDetailsArgs) GetReq() *cart.GetCartDetailsRequest {
	if !p.IsSetReq() {
		return GetCartDetailsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCartDetailsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCartDetailsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCartDetailsResult struct {
	Success *cart.GetCartDetailsResponse
}

var GetCartDetailsResult_Success_DEFAULT *cart.GetCartDetailsResponse

func (p *GetCartDetailsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCartDetailsResult) Unmarshal(in []byte) error {
	msg := new(cart.GetCartDetailsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCartDetailsResult) GetSuccess() *cart.GetCartDetailsResponse {
	if !p.IsSetSuccess() {
		return GetCartDetailsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCartDetailsResult) SetSuccess(x interface{}) {
	p.Success = x.(*cart.GetCartDetailsResponse)
}

func (p *GetCartDetailsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCartDetailsResult) GetResult() interface{} {
	return p.Success
}

func clearCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(cart.ClearCartRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cart.CartService).ClearCart(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ClearCartArgs:
		success, err := handler.(cart.CartService).ClearCart(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ClearCartResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newClearCartArgs() interface{} {
	return &ClearCartArgs{}
}

func newClearCartResult() interface{} {
	return &ClearCartResult{}
}

type ClearCartArgs struct {
	Req *cart.ClearCartRequest
}

func (p *ClearCartArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ClearCartArgs) Unmarshal(in []byte) error {
	msg := new(cart.ClearCartRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ClearCartArgs_Req_DEFAULT *cart.ClearCartRequest

func (p *ClearCartArgs) GetReq() *cart.ClearCartRequest {
	if !p.IsSetReq() {
		return ClearCartArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ClearCartArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ClearCartArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ClearCartResult struct {
	Success *cart.ClearCartResponse
}

var ClearCartResult_Success_DEFAULT *cart.ClearCartResponse

func (p *ClearCartResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ClearCartResult) Unmarshal(in []byte) error {
	msg := new(cart.ClearCartResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ClearCartResult) GetSuccess() *cart.ClearCartResponse {
	if !p.IsSetSuccess() {
		return ClearCartResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ClearCartResult) SetSuccess(x interface{}) {
	p.Success = x.(*cart.ClearCartResponse)
}

func (p *ClearCartResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ClearCartResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddToCart(ctx context.Context, Req *cart.AddToCartRequest) (r *cart.AddToCartResponse, err error) {
	var _args AddToCartArgs
	_args.Req = Req
	var _result AddToCartResult
	if err = p.c.Call(ctx, "AddToCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveFromCart(ctx context.Context, Req *cart.RemoveFromCartRequest) (r *cart.RemoveFromCartResponse, err error) {
	var _args RemoveFromCartArgs
	_args.Req = Req
	var _result RemoveFromCartResult
	if err = p.c.Call(ctx, "RemoveFromCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCartDetails(ctx context.Context, Req *cart.GetCartDetailsRequest) (r *cart.GetCartDetailsResponse, err error) {
	var _args GetCartDetailsArgs
	_args.Req = Req
	var _result GetCartDetailsResult
	if err = p.c.Call(ctx, "GetCartDetails", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ClearCart(ctx context.Context, Req *cart.ClearCartRequest) (r *cart.ClearCartResponse, err error) {
	var _args ClearCartArgs
	_args.Req = Req
	var _result ClearCartResult
	if err = p.c.Call(ctx, "ClearCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
