// Code generated by Kitex v0.15.4. DO NOT EDIT.

package cartservice

import (
	"context"
	cart "github.com/PiaoAdmin/pmall/rpc_gen/cart"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddToCart(ctx context.Context, Req *cart.AddToCartRequest, callOptions ...callopt.Option) (r *cart.AddToCartResponse, err error)
	RemoveFromCart(ctx context.Context, Req *cart.RemoveFromCartRequest, callOptions ...callopt.Option) (r *cart.RemoveFromCartResponse, err error)
	GetCartDetails(ctx context.Context, Req *cart.GetCartDetailsRequest, callOptions ...callopt.Option) (r *cart.GetCartDetailsResponse, err error)
	ClearCart(ctx context.Context, Req *cart.ClearCartRequest, callOptions ...callopt.Option) (r *cart.ClearCartResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCartServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCartServiceClient struct {
	*kClient
}

func (p *kCartServiceClient) AddToCart(ctx context.Context, Req *cart.AddToCartRequest, callOptions ...callopt.Option) (r *cart.AddToCartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddToCart(ctx, Req)
}

func (p *kCartServiceClient) RemoveFromCart(ctx context.Context, Req *cart.RemoveFromCartRequest, callOptions ...callopt.Option) (r *cart.RemoveFromCartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveFromCart(ctx, Req)
}

func (p *kCartServiceClient) GetCartDetails(ctx context.Context, Req *cart.GetCartDetailsRequest, callOptions ...callopt.Option) (r *cart.GetCartDetailsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCartDetails(ctx, Req)
}

func (p *kCartServiceClient) ClearCart(ctx context.Context, Req *cart.ClearCartRequest, callOptions ...callopt.Option) (r *cart.ClearCartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearCart(ctx, Req)
}
