// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	cart "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/cart"
	home "github.com/PiaoAdmin/gomall/app/hertz
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	home.Register(r)
	cart.Register(r)
}
