// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/auth"
	home "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/home"
	user "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	auth.Register(r)

	user.Register(r)

	home.Register(r)
}
