// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	// order "douyin-gomall/gomall/app/hertz_gateway/biz/router/order"
	order "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/order"
	auth "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/auth"
	cart "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/cart"
	category "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/category"
	checkout "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/checkout"
	home "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/home"
	product "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/product"
	user "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
<<<<<<< HEAD
	order.Register(r)
=======

>>>>>>> b6e73c27fce12b01552c5334097a847176b8f26a
	auth.Register(r)

	user.Register(r)

	checkout.Register(r)

	category.Register(r)

	product.Register(r)

	home.Register(r)
	cart.Register(r)
}
