// Code generated by hertz generator.

package product

import (
	"github.com/PiaoAdmin/gomall/app/hertz_gateway/middleware"
	"github.com/PiaoAdmin/gomall/common/constant"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _associateproductwithcategoryMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.LoginCheck("_associateproductwithcategoryMw"),
		middleware.PermissionCheck([]int32{constant.Merchant.RoleCode}),
	}
}

func _createproductMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.LoginCheck("_createproductMw"),
		middleware.PermissionCheck([]int32{constant.Merchant.RoleCode}),
	}
}
