// Code generated by Kitex v0.15.4. DO NOT EDIT.

package cart

import (
	"context"

	"github.com/cloudwego/prutal"
)

// 购物车项模型
type CartItem struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`             // 购物车项ID
	UserId   uint64 `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`   // 用户ID
	SkuId    uint64 `protobuf:"varint,3,opt,name=sku_id" json:"sku_id,omitempty"`     // SKU ID
	Quantity int32  `protobuf:"varint,4,opt,name=quantity" json:"quantity,omitempty"` // 数量

	// SKU 关联信息（从商品服务查询）
	SkuName     string `protobuf:"bytes,6,opt,name=sku_name" json:"sku_name,omitempty"`            // SKU名称
	SkuImage    string `protobuf:"bytes,7,opt,name=sku_image" json:"sku_image,omitempty"`          // SKU图片
	Price       string `protobuf:"bytes,8,opt,name=price" json:"price,omitempty"`                  // 当前价格
	MarketPrice string `protobuf:"bytes,9,opt,name=market_price" json:"market_price,omitempty"`    // 市场价
	Stock       int32  `protobuf:"varint,10,opt,name=stock" json:"stock,omitempty"`                // 库存
	SpuId       uint64 `protobuf:"varint,11,opt,name=spu_id" json:"spu_id,omitempty"`              // 关联的SPU ID
	SpuName     string `protobuf:"bytes,12,opt,name=spu_name" json:"spu_name,omitempty"`           // SPU名称
	SkuSpecData string `protobuf:"bytes,13,opt,name=sku_spec_data" json:"sku_spec_data,omitempty"` // 规格数据JSON
}

func (x *CartItem) Reset() { *x = CartItem{} }

func (x *CartItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CartItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CartItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItem) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CartItem) GetSkuImage() string {
	if x != nil {
		return x.SkuImage
	}
	return ""
}

func (x *CartItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CartItem) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *CartItem) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CartItem) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CartItem) GetSpuName() string {
	if x != nil {
		return x.SpuName
	}
	return ""
}

func (x *CartItem) GetSkuSpecData() string {
	if x != nil {
		return x.SkuSpecData
	}
	return ""
}

// 1. 添加到购物车
type AddToCartRequest struct {
	UserId   uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`   // 用户ID
	SkuId    uint64 `protobuf:"varint,2,opt,name=sku_id" json:"sku_id,omitempty"`     // SKU ID
	Quantity int32  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"` // 数量（默认为1）
}

func (x *AddToCartRequest) Reset() { *x = AddToCartRequest{} }

func (x *AddToCartRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AddToCartRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AddToCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddToCartRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AddToCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddToCartResponse struct {
	Success  bool      `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	CartItem *CartItem `protobuf:"bytes,2,opt,name=cart_item" json:"cart_item,omitempty"` // 返回添加后的购物车项
}

func (x *AddToCartResponse) Reset() { *x = AddToCartResponse{} }

func (x *AddToCartResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AddToCartResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AddToCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToCartResponse) GetCartItem() *CartItem {
	if x != nil {
		return x.CartItem
	}
	return nil
}

// 2. 从购物车移除
type RemoveFromCartRequest struct {
	UserId      uint64   `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`                    // 用户ID
	CartItemIds []uint64 `protobuf:"varint,2,rep,packed,name=cart_item_ids" json:"cart_item_ids,omitempty"` // 购物车项ID列表（支持批量删除）
}

func (x *RemoveFromCartRequest) Reset() { *x = RemoveFromCartRequest{} }

func (x *RemoveFromCartRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RemoveFromCartRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RemoveFromCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFromCartRequest) GetCartItemIds() []uint64 {
	if x != nil {
		return x.CartItemIds
	}
	return nil
}

type RemoveFromCartResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *RemoveFromCartResponse) Reset() { *x = RemoveFromCartResponse{} }

func (x *RemoveFromCartResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RemoveFromCartResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RemoveFromCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 3. 获取购物车详情
type GetCartDetailsRequest struct {
	UserId uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"` // 用户ID
}

func (x *GetCartDetailsRequest) Reset() { *x = GetCartDetailsRequest{} }

func (x *GetCartDetailsRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetCartDetailsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetCartDetailsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartDetailsResponse struct {
	Items         []*CartItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`                    // 购物车项列表
	TotalQuantity int32       `protobuf:"varint,2,opt,name=total_quantity" json:"total_quantity,omitempty"` // 总数量
	TotalAmount   string      `protobuf:"bytes,3,opt,name=total_amount" json:"total_amount,omitempty"`      // 总金额
}

func (x *GetCartDetailsResponse) Reset() { *x = GetCartDetailsResponse{} }

func (x *GetCartDetailsResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetCartDetailsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetCartDetailsResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCartDetailsResponse) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *GetCartDetailsResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

// 4. 清空购物车
type ClearCartRequest struct {
	UserId uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *ClearCartRequest) Reset() { *x = ClearCartRequest{} }

func (x *ClearCartRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ClearCartRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClearCartResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *ClearCartResponse) Reset() { *x = ClearCartResponse{} }

func (x *ClearCartResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ClearCartResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CartService interface {
	AddToCart(ctx context.Context, req *AddToCartRequest) (res *AddToCartResponse, err error)
	RemoveFromCart(ctx context.Context, req *RemoveFromCartRequest) (res *RemoveFromCartResponse, err error)
	GetCartDetails(ctx context.Context, req *GetCartDetailsRequest) (res *GetCartDetailsResponse, err error)
	ClearCart(ctx context.Context, req *ClearCartRequest) (res *ClearCartResponse, err error)
}
