// Code generated by hertz generator.

package cart

import (
	"context"

	cart "github.com/PiaoAdmin/pmall/app/api/biz/model/api/cart"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/cart"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// AddToCart .
// @router /cart/add [POST]
func AddToCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.AddToCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewAddToCartService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// RemoveFromCart .
// @router /cart/remove [POST]
func RemoveFromCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.RemoveFromCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewRemoveFromCartService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// GetCartDetails .
// @router /cart [GET]
func GetCartDetails(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.GetCartDetailsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewGetCartDetailsService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// ClearCart .
// @router /cart/clear [POST]
func ClearCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.ClearCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewClearCartService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
