// Code generated by hertz generator.

package cart

import (
	"context"

	cart "github.com/PiaoAdmin/pmall/app/api/biz/model/api/cart"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/cart"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// AddToCart .
// @Summary      添加商品到购物车
// @Description  Add sku to cart
// @Tags         Cart
// @Param        Authorization  header    string           true  "Bearer {token}"
// @Param        req            body      cart.AddToCartReq true  "Add to cart request"
// @Success      200            {object}  response.Response{data=cart.AddToCartResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /cart/add [POST]
func AddToCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.AddToCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewAddToCartService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// RemoveFromCart .
// @Summary      从购物车移除商品
// @Description  Remove skus from cart
// @Tags         Cart
// @Param        Authorization  header    string               true  "Bearer {token}"
// @Param        req            body      cart.RemoveFromCartReq true  "Remove from cart request"
// @Success      200            {object}  response.Response{data=cart.RemoveFromCartResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /cart/remove [POST]
func RemoveFromCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.RemoveFromCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewRemoveFromCartService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// GetCartDetails .
// @Summary      获取购物车详情
// @Description  Get current user's cart details
// @Tags         Cart
// @Param        Authorization  header    string  true  "Bearer {token}"
// @Success      200            {object}  response.Response{data=cart.GetCartDetailsResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /cart [GET]
func GetCartDetails(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.GetCartDetailsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewGetCartDetailsService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// ClearCart .
// @Summary      清空购物车
// @Description  Clear all items in cart
// @Tags         Cart
// @Param        Authorization  header    string  true  "Bearer {token}"
// @Success      200            {object}  response.Response{data=cart.ClearCartResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /cart/clear [POST]
func ClearCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.ClearCartReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewClearCartService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
