// Code generated by hertz generator.

package payment

import (
	"context"

	payment "github.com/PiaoAdmin/pmall/app/api/biz/model/api/payment"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/payment"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// Pay .
// @router /payment/pay [POST]
func Pay(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.PayReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewPayService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
