// Code generated by hertz generator.

package payment

import (
	"context"

	payment "github.com/PiaoAdmin/pmall/app/api/biz/model/api/payment"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/payment"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// Pay .
// @Summary      订单支付
// @Description  Pay for an order
// @Tags         Payment
// @Param        Authorization  header    string           true  "Bearer {token}"
// @Param        req            body      payment.PayReq   true  "Pay request"
// @Success      200            {object}  response.Response{data=payment.PayResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /payment/pay [POST]
func Pay(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.PayReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewPayService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
