// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	response.Success(c, utils.H{
		"message": "pong",
	})
}
