// Code generated by hertz generator.

package order

import (
	"context"

	order "github.com/PiaoAdmin/pmall/app/api/biz/model/api/order"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/order"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// PlaceOrder .
// @Summary      下单
// @Description  Place order from cart items
// @Tags         Order
// @Param        Authorization  header    string              true  "Bearer {token}"
// @Param        req            body      order.PlaceOrderReq true  "Place order request"
// @Success      200            {object}  response.Response{data=order.PlaceOrderResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /orders [POST]
func PlaceOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.PlaceOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewPlaceOrderService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// ListOrder .
// @Summary      获取订单列表
// @Description  List current user's orders
// @Tags         Order
// @Param        Authorization  header    string  true  "Bearer {token}"
// @Success      200            {object}  response.Response{data=order.ListOrderResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /orders [GET]
func ListOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.ListOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewListOrderService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}

// CancelOrder .
// @Summary      取消订单
// @Description  Cancel order by order_id
// @Tags         Order
// @Param        Authorization  header    string              true  "Bearer {token}"
// @Param        order_id       path      string              true  "Order ID"
// @Success      200            {object}  response.Response{data=order.CancelOrderResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /orders/:order_id/cancel [POST]
func CancelOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.CancelOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewCancelOrderService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
