// Code generated by Kitex v0.15.4. DO NOT EDIT.

package user

import (
	"context"

	"github.com/cloudwego/prutal"
)

// 脱敏
type User struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone    string `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=avatar" json:"avatar,omitempty"`
	Status   int32  `protobuf:"varint,6,opt,name=status" json:"status,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RegisterRequest struct {
	Username        string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password        string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Email           string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	PasswordConfirm string `protobuf:"bytes,4,opt,name=password_confirm" json:"password_confirm,omitempty"`
}

func (x *RegisterRequest) Reset() { *x = RegisterRequest{} }

func (x *RegisterRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPasswordConfirm() string {
	if x != nil {
		return x.PasswordConfirm
	}
	return ""
}

type RegisterResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *RegisterResponse) Reset() { *x = RegisterResponse{} }

func (x *RegisterResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() { *x = LoginRequest{} }

func (x *LoginRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *LoginResponse) Reset() { *x = LoginResponse{} }

func (x *LoginResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	UserId   uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Phone    string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
	Avatar   string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
	Username string `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
}

func (x *UpdateUserRequest) Reset() { *x = UpdateUserRequest{} }

func (x *UpdateUserRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUserResponse struct {
	Success bool  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	User    *User `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"` // 返回更新后的最新数据
}

func (x *UpdateUserResponse) Reset() { *x = UpdateUserResponse{} }

func (x *UpdateUserResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateUserResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdatePasswordRequest struct {
	UserId      uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=old_password" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password" json:"new_password,omitempty"`
}

func (x *UpdatePasswordRequest) Reset() { *x = UpdatePasswordRequest{} }

func (x *UpdatePasswordRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UpdatePasswordRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdatePasswordRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *UpdatePasswordResponse) Reset() { *x = UpdatePasswordResponse{} }

func (x *UpdatePasswordResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UpdatePasswordResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdatePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserInfoRequest struct {
	UserId uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetUserInfoRequest) Reset() { *x = GetUserInfoRequest{} }

func (x *GetUserInfoRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserInfoRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserInfoRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *GetUserInfoResponse) Reset() { *x = GetUserInfoResponse{} }

func (x *GetUserInfoResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserInfoResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserInfoResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserService interface {
	Register(ctx context.Context, req *RegisterRequest) (res *RegisterResponse, err error)
	Login(ctx context.Context, req *LoginRequest) (res *LoginResponse, err error)
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (res *GetUserInfoResponse, err error)
	UpdateUser(ctx context.Context, req *UpdateUserRequest) (res *UpdateUserResponse, err error)
	UpdatePassword(ctx context.Context, req *UpdatePasswordRequest) (res *UpdatePasswordResponse, err error)
}
