// Code generated by Kitex v0.15.4. DO NOT EDIT.

package checkout

import (
	"context"

	"github.com/cloudwego/prutal"
)

type Address struct {
	StreetAddress string `protobuf:"bytes,1,opt,name=street_address" json:"street_address,omitempty"`
	City          string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ZipCode       int32  `protobuf:"varint,4,opt,name=zip_code" json:"zip_code,omitempty"`
}

func (x *Address) Reset() { *x = Address{} }

func (x *Address) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Address) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Address) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

type CheckoutItem struct {
	SkuId    uint64 `protobuf:"varint,1,opt,name=sku_id" json:"sku_id,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *CheckoutItem) Reset() { *x = CheckoutItem{} }

func (x *CheckoutItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckoutItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckoutItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CheckoutItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckoutItemResult struct {
	SkuId       uint64 `protobuf:"varint,1,opt,name=sku_id" json:"sku_id,omitempty"`
	Quantity    int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	SkuName     string `protobuf:"bytes,3,opt,name=sku_name" json:"sku_name,omitempty"`
	SkuImage    string `protobuf:"bytes,4,opt,name=sku_image" json:"sku_image,omitempty"`
	Price       string `protobuf:"bytes,5,opt,name=price" json:"price,omitempty"`
	MarketPrice string `protobuf:"bytes,6,opt,name=market_price" json:"market_price,omitempty"`
	SpuId       uint64 `protobuf:"varint,7,opt,name=spu_id" json:"spu_id,omitempty"`
	SkuSpecData string `protobuf:"bytes,8,opt,name=sku_spec_data" json:"sku_spec_data,omitempty"`
}

func (x *CheckoutItemResult) Reset() { *x = CheckoutItemResult{} }

func (x *CheckoutItemResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckoutItemResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckoutItemResult) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CheckoutItemResult) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckoutItemResult) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CheckoutItemResult) GetSkuImage() string {
	if x != nil {
		return x.SkuImage
	}
	return ""
}

func (x *CheckoutItemResult) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CheckoutItemResult) GetMarketPrice() string {
	if x != nil {
		return x.MarketPrice
	}
	return ""
}

func (x *CheckoutItemResult) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CheckoutItemResult) GetSkuSpecData() string {
	if x != nil {
		return x.SkuSpecData
	}
	return ""
}

type CheckoutRequest struct {
	UserId          uint64          `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Items           []*CheckoutItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	ShippingAddress *Address        `protobuf:"bytes,3,opt,name=shipping_address" json:"shipping_address,omitempty"`
	CreditCard      string          `protobuf:"bytes,4,opt,name=credit_card" json:"credit_card,omitempty"`
}

func (x *CheckoutRequest) Reset() { *x = CheckoutRequest{} }

func (x *CheckoutRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckoutRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckoutRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckoutRequest) GetItems() []*CheckoutItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckoutRequest) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *CheckoutRequest) GetCreditCard() string {
	if x != nil {
		return x.CreditCard
	}
	return ""
}

type CheckoutResponse struct {
	OrderId     string                `protobuf:"bytes,1,opt,name=order_id" json:"order_id,omitempty"`
	TotalAmount string                `protobuf:"bytes,2,opt,name=total_amount" json:"total_amount,omitempty"`
	Items       []*CheckoutItemResult `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

func (x *CheckoutResponse) Reset() { *x = CheckoutResponse{} }

func (x *CheckoutResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckoutResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckoutResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CheckoutResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CheckoutResponse) GetItems() []*CheckoutItemResult {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckoutService interface {
	Checkout(ctx context.Context, req *CheckoutRequest) (res *CheckoutResponse, err error)
}
