// Code generated by hertz generator.

package checkout

import (
	"context"

	checkout "github.com/PiaoAdmin/pmall/app/api/biz/model/api/checkout"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/checkout"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// Checkout .
// @Summary      结算下单
// @Description  Checkout with cart items, create order and pay
// @Tags         Checkout
// @Param        Authorization  header    string               true  "Bearer {token}"
// @Param        req            body      checkout.CheckoutReq true  "Checkout request"
// @Success      200            {object}  response.Response{data=checkout.CheckoutResp}
// @Failure      400            {object}  response.Response{data=string}  "Bad Request"
// @Failure      500            {object}  response.Response{data=string}  "Internal Server Error"
// @router /checkout [POST]
func Checkout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req checkout.CheckoutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewCheckoutService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
