// Code generated by hertz generator.

package checkout

import (
	"context"

	checkout "github.com/PiaoAdmin/pmall/app/api/biz/model/api/checkout"
	service "github.com/PiaoAdmin/pmall/app/api/biz/service/checkout"
	"github.com/PiaoAdmin/pmall/app/api/pkg/response"
	"github.com/cloudwego/hertz/pkg/app"
	herrors "github.com/cloudwego/hertz/pkg/common/errors"
)

// Checkout .
// @router /checkout [POST]
func Checkout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req checkout.CheckoutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		_ = c.Error(err).SetType(herrors.ErrorTypeBind)
		return
	}

	resp, err := service.NewCheckoutService(ctx, c).Run(&req)
	if err != nil {
		_ = c.Error(err)
		return
	}

	response.Success(c, resp)
}
