// Code generated by hertz generator.

package auth

import (
	"github.com/PiaoAdmin/gomall/app/hertz_gateway/middleware"
	"github.com/PiaoAdmin/gomall/common/constant"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.LoginCheck("_logoutMw"),
	}
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifytokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.LoginCheck("_roleMw"),
		middleware.PermissionCheck([]int32{constant.Admin.RoleCode}),
	}
}

func _adduserroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removeuserroleMw() []app.HandlerFunc {
	// your code...
	return nil
}
