// Code generated by Kitex v0.15.4. DO NOT EDIT.

package paymentservice

import (
	"context"
	"errors"
	payment "github.com/PiaoAdmin/pmall/rpc_gen/payment"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Pay": kitex.NewMethodInfo(
		payHandler,
		newPayArgs,
		newPayResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*payment.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "payment",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func payHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.PayRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).Pay(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PayArgs:
		success, err := handler.(payment.PaymentService).Pay(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PayResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPayArgs() interface{} {
	return &PayArgs{}
}

func newPayResult() interface{} {
	return &PayResult{}
}

type PayArgs struct {
	Req *payment.PayRequest
}

func (p *PayArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PayArgs) Unmarshal(in []byte) error {
	msg := new(payment.PayRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PayArgs_Req_DEFAULT *payment.PayRequest

func (p *PayArgs) GetReq() *payment.PayRequest {
	if !p.IsSetReq() {
		return PayArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PayArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PayResult struct {
	Success *payment.PayResponse
}

var PayResult_Success_DEFAULT *payment.PayResponse

func (p *PayResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PayResult) Unmarshal(in []byte) error {
	msg := new(payment.PayResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PayResult) GetSuccess() *payment.PayResponse {
	if !p.IsSetSuccess() {
		return PayResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PayResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.PayResponse)
}

func (p *PayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PayResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Pay(ctx context.Context, Req *payment.PayRequest) (r *payment.PayResponse, err error) {
	var _args PayArgs
	_args.Req = Req
	var _result PayResult
	if err = p.c.Call(ctx, "Pay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
