// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listbrandsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _skusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchupdateskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethomeproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}
