// Code generated by Kitex v0.15.4. DO NOT EDIT.

package order

import (
	"context"

	"github.com/cloudwego/prutal"
)

// 地址不用存 每次下单时填写
type Address struct {
	StreetAddress string `protobuf:"bytes,1,opt,name=street_address" json:"street_address,omitempty"`
	City          string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ZipCode       int32  `protobuf:"varint,4,opt,name=zip_code" json:"zip_code,omitempty"`
}

func (x *Address) Reset() { *x = Address{} }

func (x *Address) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Address) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Address) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

type CartItem struct {
	SkuId    uint64 `protobuf:"varint,1,opt,name=sku_id" json:"sku_id,omitempty"`     // SKU ID
	Quantity int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"` // 数量
	SkuName  string `protobuf:"bytes,3,opt,name=sku_name" json:"sku_name,omitempty"`  // SKU名称
	Price    string `protobuf:"bytes,4,opt,name=price" json:"price,omitempty"`        // 当前价格
}

func (x *CartItem) Reset() { *x = CartItem{} }

func (x *CartItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CartItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CartItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CartItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type PlaceOrderReq struct {
	UserId          uint64      `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Email           string      `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Items           []*CartItem `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	ShippingAddress *Address    `protobuf:"bytes,4,opt,name=shipping_address" json:"shipping_address,omitempty"`
}

func (x *PlaceOrderReq) Reset() { *x = PlaceOrderReq{} }

func (x *PlaceOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PlaceOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PlaceOrderReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceOrderReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PlaceOrderReq) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlaceOrderReq) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

type OrderResult struct {
	OrderId string `protobuf:"bytes,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *OrderResult) Reset() { *x = OrderResult{} }

func (x *OrderResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OrderResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OrderResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PlaceOrderResp struct {
	Order *OrderResult `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
}

func (x *PlaceOrderResp) Reset() { *x = PlaceOrderResp{} }

func (x *PlaceOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PlaceOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PlaceOrderResp) GetOrder() *OrderResult {
	if x != nil {
		return x.Order
	}
	return nil
}

type Order struct {
	Items           []*CartItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	OrderId         string      `protobuf:"bytes,2,opt,name=order_id" json:"order_id,omitempty"`
	UserId          uint64      `protobuf:"varint,3,opt,name=user_id" json:"user_id,omitempty"`
	Email           string      `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	ShippingAddress *Address    `protobuf:"bytes,5,opt,name=shipping_address" json:"shipping_address,omitempty"`
	Status          string      `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	CreatedAt       int32       `protobuf:"varint,7,opt,name=created_at" json:"created_at,omitempty"`
}

func (x *Order) Reset() { *x = Order{} }

func (x *Order) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Order) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Order) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Order) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListOrderReq struct {
	UserId uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *ListOrderReq) Reset() { *x = ListOrderReq{} }

func (x *ListOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListOrderReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListOrderResp struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (x *ListOrderResp) Reset() { *x = ListOrderResp{} }

func (x *ListOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListOrderResp) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type MarkOrderPaidReq struct {
	UserId  uint64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	OrderId string `protobuf:"bytes,2,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *MarkOrderPaidReq) Reset() { *x = MarkOrderPaidReq{} }

func (x *MarkOrderPaidReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MarkOrderPaidReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MarkOrderPaidReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkOrderPaidReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type MarkOrderPaidResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *MarkOrderPaidResp) Reset() { *x = MarkOrderPaidResp{} }

func (x *MarkOrderPaidResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MarkOrderPaidResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MarkOrderPaidResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelOrderReq struct {
	OrderId string `protobuf:"bytes,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *CancelOrderReq) Reset() { *x = CancelOrderReq{} }

func (x *CancelOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CancelOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CancelOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *CancelOrderResp) Reset() { *x = CancelOrderResp{} }

func (x *CancelOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CancelOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CancelOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OrderService interface {
	ListOrder(ctx context.Context, req *ListOrderReq) (res *ListOrderResp, err error)
	CancelOrder(ctx context.Context, req *CancelOrderReq) (res *CancelOrderResp, err error)
	PlaceOrder(ctx context.Context, req *PlaceOrderReq) (res *PlaceOrderResp, err error)
	MarkOrderPaid(ctx context.Context, req *MarkOrderPaidReq) (res *MarkOrderPaidResp, err error)
}
